### ISSUE TITLE
Big problem: Page list suddenly reset!

### ISSUE THREAD

**Issue by Cameliar** [sneakypete81/updatescanner#100]
Hi,
I was using Update scanner since a few weeks in my Firefox browser on Windows 10. Today (maybe when another add-on, Xmarks, was syncronizing), the page list is suddenly reset and no page is showed. How can I recover all my pages? Is very important, I was using them for my job. Hope you can give me and hand!

Edit: I checked the profile folder in Firefox. There is a folder called "update scanner" where are various files .new and .old. I guess they are all my saved sites. What I tried: restart pc, disable updatescanner + restart Firefox and activate US again, but the page list is still empty. Any suggestion?

**Comment by sneakypete81** [comment]
The page list is stored as bookmarks in a folder called "Update Scanner's Pages". It sounds possible that Xmarks might have deleted them somehow while syncing.

You can try restoring your bookmarks from a backup:
https://support.mozilla.org/kb/restore-bookmarks-from-backup-or-move-them

**Comment by Cameliar** [comment]
Hello sneakypete, many thanks for your help!! It worked and my list is there again. I hope that in future UpdateScanner will have an internal way to backup lists.
Bye

**Comment by sneakypete81** [comment]
Ok, glad it worked!
