### ISSUE TITLE
Update Scanners Stopped Working

### ISSUE THREAD

**Issue by mcmedal001** [sneakypete81/updatescanner#101]
I can't figure what the issue is with Update Scanner on Firefox. I won't list the sites I am monitoring, when you click the add, delete and other buttons (except preferences), nothing happens.

I deleted it and installed again, that did not fix it. Is this a know issue or I am alone?

I will be glad to get any help. Thank you.

**Comment by sneakypete81** [comment]
Could you please give your Firefox version, Update Scanner version and OS?

Update Scanner stores its site list as bookmarks in a folder called "Update Scanner's Pages". Do you see the sites in your bookmarks in that folder?

Does it work if you install Update Scanner in a fresh profile? (see https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles),

**Comment by mcmedal001** [comment]
Q: Could you please give your Firefox version, Update Scanner version and OS?
ANS: Latest version of Firefox 53.0.3, Update Scanner 3.3.2, Mac OS Sierra

Q: Update Scanner stores its site list as bookmarks in a folder called "Update Scanner's Pages". Do you see the sites in your bookmarks in that folder?
ANS: Yes, the folder and the pages are still there.

Q: Does it work if you install Update Scanner in a fresh profile?
ANS: I will try this and update this post.

**Comment by sneakypete81** [comment]
Ok, thanks. I don't have access to a Mac, but will try to help debug it with you. It sounds like something has become corrupted in your profile.

Can you think of anything that happened recently that might be related to the problem?

Do you see any errors appear in the Browser Console (https://developer.mozilla.org/docs/Tools/Browser_Console) when you open the Update Scanner sidebar?
