### ISSUE TITLE
Add "feature" to ignore some parts of the website as being updated

### ISSUE THREAD

**Issue by Quix0r** [sneakypete81/updatescanner#105]
E.g. If you monitor your releases page here on github [1] you may noptice that it has detected a change when you login and logout. Of course, there is a change because the DOM document has changed.

What I want is, that updatescanner ignores such divs (by id/class) for changes as they will always change (being logged out and then login).

The "bug" (yes, it is no bug, it is a feature) can easily reproduced:

1) Add [1] to your monitored websites
2) Force-update ("Jetzt prüfen" in German version)
3) If no change shows up, logout from github and do step 2) again.

You will then see that it lets you know that there was a change, but surely you only logged out.

A fix would be to tell updatescanner to ignore certain tags on a per-site id/class basis like ublock does.

Examples:

- example.com##.foo = ignores all tags with at least class="foo" on entire website example.com, including sub-domains
- example.org###bar = ignores "all" tags with id="bar" on entire website example.com, including sub-domains
- bazz.example.com##.bazz (ignores all tags with at least class="bazz" on subdomain bazz.example.com

1: https://github.com/sneakypete81/updatescanner/releases

**Comment by sneakypete81** [comment]
Thanks for taking the time to report this so clearly. I think this is covered by #9.

**Comment by Quix0r** [comment]
Is there then a (ublock-compatible) file where I can put my rules in or can I load my rules file directly?
