### ISSUE TITLE
Fails to work with latest Firefox Nightlies

### ISSUE THREAD

**Issue by djryan** [sneakypete81/updatescanner#106]
As of **57.0a1 (2017-08-09) (64-bit)**, clicking scan no-longer scans a page for changes.  Clicking a page pops out, but no longer displays anything other than a blank screen and `chrome://updatescan` URI.

**Comment by sneakypete81** [comment]
Firefox 57 has removed support for XUL addons, so Update Scanner will no longer work.
#82 is an attempt to port this addon to a WebExtension, but progress has been pretty slow recently.
