### ISSUE TITLE
Data loss

### ISSUE THREAD

**Issue by konzeptlos** [sneakypete81/updatescanner#107]
Hello!

It's my first time posting here - but I just didn't found any solution by now...
All data in "update scanner" is lost from one day to another - all web pages saved over years (!) are deleted.
Has anybody an idea where perhaps the data from "update scanner" was saved, so that I can find them? Thanks a lot!

Bye, Chris

**Comment by sneakypete81** [comment]
The pages are stored in your bookmarks, in a folder called "Update Scanner's Pages".
See https://support.mozilla.org/kb/restore-bookmarks-from-backup-or-move-them.
