### ISSUE TITLE
Update Scanner 3.3.3beta 1 bug?  This link requires java.

### ISSUE THREAD

**Issue by molitar** [sneakypete81/updatescanner#108]
I keep getting link requires java but if I than go click on show current page > rescan the page > it than starts to work properly again.

**Comment by molitar** [comment]
Any update for this error..  

Javascript is required. Please enable javascript before you are allowed to see this page.

**Comment by sneakypete81** [comment]
Unfortunately Update Scanner only scans HTML, so can't be used for websites that require Javascript to see the content (see #83).
