### ISSUE TITLE
[webext] CSP blocks script from the extension

### ISSUE THREAD

**Issue by StoyanDimitrov** [sneakypete81/updatescanner#112]
Here is the corresponding log of the extension debug console (the text is retranslated to English so it will not reflect what you see in your console but conveys the meaning):

```
Content Security Policy: Page settings block loading the resource blob:moz-extension://[UUID 1]/[UUID 2] („script-src moz-extension://[UUID 1]“).  (unknown)
Unknown node type: undefined  sidebar_script.js:78:3
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource address: moz-extension://[UUID 1]/app/sidebar/sidebar_script.js
Source map location: sidebar_script.js.map[Learn more]  (unknown)
Pages to autoscan: 23  background_script.js:78:3
Scanning "some page title here"...  background_script.js:78:3
Scanning "some page title here"...  background_script.js:78:3
Scanning "some page title here"...  background_script.js:78:3
Scanning "some page title here"...  background_script.js:78:3
```

The blocked script, as I can say, is jqtree related and starts with `self.onmessage = function`.

Tested on latest Nightly 58.0a1 (2017-11-07) (64) with clean profile running under Win10.

**Comment by sneakypete81** [comment]
Thanks, I'll take a look.

**Comment by sneakypete81** [comment]
@StoyanDimitrov, what is actually wrong? It sounds like a sidebar problem, can you post a screenshot showing the issue?

**Comment by Keith94** [comment]
Same issue, sidebar contents are not displayed and is stuck on "loading.." if CSP is enabled.

>Cannot send message: Other side disconnected: ["MessageChannel:Response", {result:0, messageName:687194777168, recipient:{}, value:{}}]  ExtensionUtils.jsm:519
Cannot send function call result: other side closed connection (call data: ({path:"storage.sync.get", args:[["utwe-delay", "utwe-autohide", "utwe-autohide-delay", "utwe-skip-hash", "utwe-trim-file", "utwe-double-decode", "utwe-skip-js", "utwe-font-size", "utwe-hide-status", "utwe-compiled-template"]]}))
Content Security Policy: The page’s settings blocked the loading of a resource at blob:moz-extension://2a4532b2-8aaa-4d72-8310-3ecb940cb49a/6e54865a-37a9-4b0e-8f05-0582a48ad6e6 (“script-src moz-extension://2a4532b2-8aaa-4d72-8310-3ecb940cb49a”).

![image](https://user-images.githubusercontent.com/5490615/32540376-663bf15c-c421-11e7-800c-fe5d2903eccd.png)

Workaround: Set `security.csp.enable` to false in about:config.

**Comment by sneakypete81** [comment]
Ok, thanks. I see this on the latest nightly, but not the Firefox 57 beta.
