### ISSUE TITLE
Support 404

### ISSUE THREAD

**Issue by gdevitis** [sneakypete81/updatescanner#116]
In the previous version of Update Scanner, when the site was not reachable due to a 404 error, the corresponding string became faint. When the site was back attainable, the corresponding string became black and this allowed the user to understand that the site had been created or was valid. I used it a lot to monitor the pages of Mozilla changelogs and their ftp servers on new versions. Can this media be reintroduced? In addition, you can add a modified site notification also for this case in such a way that you do not have to check the sidebar.

**Comment by sneakypete81** [comment]
Thanks for your comment, it's useful to hear how people are using Update Scanner.

I'll have to think about the notification, since it could easily be confusing for people who expect it to indicate that a page has been updated. But greying out sites that can't be reached is a useful feature.

**Comment by sneakypete81** [comment]
Added to 4.0.1beta1
