### ISSUE TITLE
Page list backup and restore

### ISSUE THREAD

**Issue by jfg001** [sneakypete81/updatescanner#117]
Hello
how to export bookmarks updatescanner 4.00 for re-installation complete firefox 57 ?
best regards
jf

**Comment by sneakypete81** [comment]
If you open the Update Scanner sidebar in v4.0.0, you'll see a link to a page that lets you import pages from the previous version of Update Scanner. Is that what you are asking?

**Comment by jfg001** [comment]
I installed ff57 and update scanner 4.0. I imported the bookmarks of the previous version.
now i will want to back up the update scanner 4.0 database for future backup and re-installation in a clean firefox 57.

**Comment by sneakypete81** [comment]
Ah, I understand. Backup/restore is not implemented yet.

**Comment by yermulnik** [comment]
+1 for this feature

**Comment by jfg001** [comment]
all that remains is this important import-export function to realize for me to abandon FF56 and the old application. For the rest with the beta 4.01, it's perfect.
thank you for your work

**Comment by sneakypete81** [comment]
Please try 4.2.0beta1 (see #36) and let me know if you have any problems.

**Comment by yermulnik** [comment]
You've got yet another beta tester =)
Tried «`Backup Pages`» and it works. Haven't tried to restore though.

Wishlist (if you don't mind):

- File naming template (as I'd prefer to have lowercase names with spaces replaced by hyphens and suffixed with current date; e.g. `update-scanner-backup-%Y-%m-%d.json`)
- Option to do a **full** backup which includes downloaded pages.

Let me know if any of these is doable and if I'd better create separate issues for this.

**Comment by sneakypete81** [comment]
Including a timestamp in the filename seems like a good idea. I'm not sure that backing up downloaded pages is practical though.

**Comment by sneakypete81** [comment]
Implemented in v4.2.0.
