### ISSUE TITLE
Login cookies not sent

### ISSUE THREAD

**Issue by WHRoeder1** [sneakypete81/updatescanner#119]
Output from mql5.com shows login button and corresponding formatting
US 4.0.0 FF 57.0

**Comment by sneakypete81** [comment]
Probably not possible, since the background scan process doesn't share cookies with the main browsing session. Perhaps #56 will help for some cases?

**Comment by drumsibumsi** [comment]
What kind of bullshit security policy is that on a new Firefox? :O I can't even click links on scanned pages. Also, cannot open pages' current version so that I could click links.

**Comment by sneakypete81** [comment]
For your other points, please see #122 and #120 (click the page title to go to the website itself).

**Comment by Moini** [comment]
Would it be possible to manually define cookies, then? I could export and import, or something like that - I know this would need to be repeated now and then...
