### ISSUE TITLE
List of pages to scan is empty after update to 4.0.0beta6 in Firefox 56.0

### ISSUE THREAD

**Issue by Johann-Tree** [sneakypete81/updatescanner#121]
After the update to version 4.0.0beta6 using Firefox 56.0 on Ubuntu 16.04.3 LTS the list of pages to scan is empty. The bookmark folder “Update Scanner's Pages” still exists and contains all pages to scan. 
When clicking Menu -> Scan all pages, the browser console says:

> Pages to manually scan: 0  background_script.js:78:3
> Manual scan complete, 0 new changes detected.

Thanks for this great AddOn and porting it to work as webextension!

**Comment by WHRoeder1** [comment]
Open the side bar and read what it says.
1) Show Bookmarks -> Import and Backup -> Backup (to desktop)
2) Click Import -> select Bookmarkts*.json

**Comment by Johann-Tree** [comment]
When clicking the Sidebar button, I'm getting:

> Sorry, this button only works in Firefox 57 and above.

**Comment by sneakypete81** [comment]
Please upgrade to Firefox 57 and try again. As WHRoeder says, open the Update Scanner sidebar, follow the upgrade link, and you'll see instructions for how to import your previous list of pages.
