### ISSUE TITLE
Content Security Policy Error when clicking links

### ISSUE THREAD

**Issue by WHRoeder1** [sneakypete81/updatescanner#122]
Hover over a link on the changes page. The status bar shows the correct URL.
Control Left Click or Control Shift Left Click, opens the URL in a separate tab. No problem.
Plain Left Click, blanks the page except for the US header. 
On blank section, Right click -> this frame ->view page source show correct HTML and URL reads view-source:https://correctURL This may be a FF issue not US.

**Comment by sneakypete81** [comment]
Thanks, I noticed this too - I'll take a look at how to work around this.

**Comment by sneakypete81** [comment]
As mentioned, you can work around this for now by opening links in a new tab,

**Comment by sneakypete81** [comment]
Fixed in 4.0.1beta2
