### ISSUE TITLE
Scan Individual Folders/Pages

### ISSUE THREAD

**Issue by RVRover** [sneakypete81/updatescanner#123]
Is there a way to manually scan individual folders in the new version?  That's a pretty important feature for me.

**Comment by sneakypete81** [comment]
Thanks, this still needs implementing - I agree, this will be a useful feature.

**Comment by Keith94** [comment]
Scanning individual pages would be useful too.

**Comment by sneakypete81** [comment]
This is now available in 4.3.0beta1 - right-click on an item in the sidebar and select "Scan Now".
See #36 for beta installation instructions.

This has involved several changes to the scanning code, so please let me know below if this works for you.

**Comment by Keith94** [comment]
Confirmed fixed. :+1:

**Comment by RVRover** [comment]
Ah!  I see that now! Excellent! Very helpful!

**Comment by sneakypete81** [comment]
Fixed in 4.3.0
