### ISSUE TITLE
How to return to prior version

### ISSUE THREAD

**Issue by RVRover** [sneakypete81/updatescanner#125]
Where can I find the prior version of Update Scanner?  Ver. 4 isn't working for me and I need to downgrade.

**Comment by silentbrains** [comment]
[https://addons.mozilla.org/en-US/firefox/addon/update-scanner/versions/](url)

**Comment by sneakypete81** [comment]
Use v3.3.2 (XUL extension) with Firefox versions up to FF56 (Firefox ESR, for example).
Use v4.x.x (WebExtension) with Firefox versions FF57 and above.
