### ISSUE TITLE
Firefox Quantum and older version

### ISSUE THREAD

**Issue by yolinfl** [sneakypete81/updatescanner#128]
I've deinstalled FF Quantum (57) due to issues with some plugins.
I've reinstalled FF 55 but still Update Scanner is not working.
What is the lastest version, besides the FF Quantum, that Update Scanner will work properly?

**Comment by sneakypete81** [comment]
Version 3.2.2 - see https://addons.mozilla.org/en-US/firefox/addon/update-scanner/versions/
