### ISSUE TITLE
Tab title should include page title

### ISSUE THREAD

**Issue by bahnbino** [sneakypete81/updatescanner#129]
The URL displayed for a changed site does not contain the URL of the actual page, like it used to be.

**Comment by sneakypete81** [comment]
Could you explain more clearly what you expect to see? 

If you hover the mouse over the title ("Update Scanner Website" in the image below), you will see the URL appear at the bottom of the window.

![image](https://user-images.githubusercontent.com/38854/32936835-c89cc4f4-cb6d-11e7-91d7-371173c0929e.png)

**Comment by bahnbino** [comment]
it used to say the name of the site on the tab, instead of saying "Update Scanner" on the tab....that is what I want

**Comment by sneakypete81** [comment]
Understood - thanks. I agree, this would be a good thing to fix.

**Comment by sneakypete81** [comment]
Fixed in 4.0.1beta2

**Comment by bahnbino** [comment]
Wow, cool! Any idea when I an see this in action?

**Comment by sneakypete81** [comment]
You can install it now from the [Beta page](https://addons.mozilla.org/en-US/firefox/addon/update-scanner/versions/beta).
