### ISSUE TITLE
Text of sites not appearing (Javascript)

### ISSUE THREAD

**Issue by bahnbino** [sneakypete81/updatescanner#130]
The text of sites with changes are not appearing, making it impossible to see the changes, if there are any.

**Comment by sneakypete81** [comment]
Please upload a screenshot and URL of a page that's not working.

**Comment by bahnbino** [comment]
https://pcaobus.org/Pages/default.aspx
![missing text](https://user-images.githubusercontent.com/33730355/32950758-863a8aee-cb75-11e7-8f21-f7be1752054c.png)

Text missing is the middle

**Comment by sneakypete81** [comment]
Unfortunately Update Scanner only scans HTML, so can't be used for websites that require Javascript to see the content. See #83.

You can see this by installing https://addons.mozilla.org/firefox/addon/javascript-toggler/, going to the URL you provided, then turning off Javascript. The pages looks the same as the screenshot you provided.

**Comment by bahnbino** [comment]
Hmm, before Quantum we did not have this issue with Update Scanner, but if there is no fix, then that's that.
