### ISSUE TITLE
New update scanner icon doesn't change color when there are changes

### ISSUE THREAD

**Issue by slcpunk** [sneakypete81/updatescanner#132]
FF just updated, add on updated to new "side bar" thingy.  The icon in the toolbar used to change color when there were pending/unviewed changes.  Pretty handy, lost functionality in "upgrade".

**Comment by sneakypete81** [comment]
The icon doesn't change colour, but instead you should see a big red badge with the number of updated pages. Is this working for you?

![image](https://user-images.githubusercontent.com/38854/32937109-eb63cb26-cb6e-11e7-8dc9-8065135d80e0.png)

**Comment by slcpunk** [comment]
OH!  Awesome!  I shouldn't have doubted it.  Hadn't seen it yet, but I take your word for it.
