### ISSUE TITLE
Firefox 57.0 Quantum

### ISSUE THREAD

**Issue by yermulnik** [sneakypete81/updatescanner#133]
I've just updated to Firefox 57.0 Quantum on my Ubuntu-based distro and extension just doesn't work at all. I've lost all of my sites to scan for updates (is there a way to somehow export/import those to FF 57?). «`New`» button does nothing. «`Sidebar`» button yields it works only in FF 57 and above. What is wrong with my installation?

**Comment by sneakypete81** [comment]
Sorry this isn't working for you. Could you please try:
* Restart Firefox
* Open the Browser Console
* Click the Update Scanner toolbar icon and then the "New" button

Then copy/paste the contents of the Console here.

Please also try [creating a new Firefox profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles), and see if that fixes the problem.

**Comment by yermulnik** [comment]
Seems like I've managed to get everything settled down (not only with this extensions).
But is there a way to export/import/restore list of monitored sites from FF 56 to FF 57?
I've got a lot of monitored pages and it's a nightmare to loose them all =(
I've found where Update Scanner keeps old and new versions of pages (at least for FF 56), but I was not able to find where does it keep sites URLs and scan settings.
Appreciate your assistance.

**Comment by sneakypete81** [comment]
Glad it's working now - that was a strange problem.

When you open the Update Scanner sidebar, you should see a link to "Upgrade to Update Scanner 4" (it is shown if you have fewer than 5 pages in the sidebar). Click the link, and follow the instructions to import your pages from the previous extension.

![image](https://user-images.githubusercontent.com/38854/32938694-f4d1a452-cb74-11e7-8d0f-5fc3e4b1fc15.png)

**Comment by yermulnik** [comment]
Wow! It's a magic! God bless you, man! =)
Looks like Update Scanner has some issues with pages with non-utf charset, e.g. `windows-1251`. When you've got chance I'd appreciate if you can take a look. Thanks for the great job you do!

**Comment by sneakypete81** [comment]
Yes, character set support is not yet implemented. Please open a new issue, including the URL of the page that is causing problems.
