### ISSUE TITLE
Scan List disappeared

### ISSUE THREAD

**Issue by munkeyman2** [sneakypete81/updatescanner#134]
I can't access my scan list after Firefox update. Anybody know where I can find a copy of it? Is it located in a directory somewhere?

**Comment by sneakypete81** [comment]
You'll need to import the scanlist manually:
* Open the Update Scanner sidebar
* Click the "Upgrade to Update Scanner 4" link
* Follow the instructions

The Upgrade link will only appear if you have fewer than 5 pages in the sidebar.
