### ISSUE TITLE
Cookie not used in v4.0.0?

### ISSUE THREAD

**Issue by yermulnik** [sneakypete81/updatescanner#137]
In previous versions of Update Scanner and FF it was possible to check for updates of pages where user had/is logged in to. Probably based on cookies saved by FF (I might be wrong). In new version of Update Scanner this feature doesn't work anymore and Update Scanner discovers the login page instead of content which is available for logged in users.

**Comment by sneakypete81** [comment]
In the new WebExtension environment, cookies aren't shared between the background process and the main browsing session. I'm not sure that there's any way around this, but maybe #56 will help for some pages.

**Comment by yermulnik** [comment]
FF57 is quite fast comparing to previous versions, but webextensions make so many troubles for things we used to use =(
Thanks for doing this great job trying to struggle Update Scanner through this nightmare!

**Comment by KaosDragon** [comment]
Is there no way to give the background process it's own cookies or something?
