### ISSUE TITLE
Show All Updates hidden with 23+ items

### ISSUE THREAD

**Issue by WHRoeder1** [sneakypete81/updatescanner#138]
With 23+ items the blue show all isn't visible. With 22 items it is partially visible
![capture2](https://user-images.githubusercontent.com/33694158/32982066-98e6e5a2-cc4c-11e7-809e-199cb58061bd.PNG)

**Comment by sneakypete81** [comment]
Whoops! Thanks, looks like that needs a tweak.

**Comment by sneakypete81** [comment]
Fixed in 4.0.1beta2

**Comment by WHRoeder1** [comment]
4.2.0 is working fine for me
