### ISSUE TITLE
Failed to import bookmarks during upgrade

### ISSUE THREAD

**Issue by charlieseelig** [sneakypete81/updatescanner#139]
Probably missed a step in the new setup due to the update in Firefox, but I tried to follow the instructions, exporting the bookmarks, then importing them using the link in the instructions for Update Scanner. However, I ended up with none of the pages being imported and about 50 or so "New Pages", not connected to any particular pages. I can see the list of bookmarks in the Update Scanner folder, set up before the update in Firefox, but don't see a way of trying again to import them. Suggestions - Thanks, Charlie

**Comment by sneakypete81** [comment]
Please either post your bookmarks .JSON file here, or email it to updatescanner@gmail.com, and I'll take a look.

**Comment by charlieseelig** [comment]
I've e-mailed you the bookmark file. When I tried to attach it here, the site indicated that it did not support the JSON file type.

**Comment by Mirelore1** [comment]
I have the same problem, after upgrade and bookmarks imported, under Update Scanner more than half of them are New Page even if in Bookmarks all of pages are imported. ![1](https://user-images.githubusercontent.com/33838827/33027719-94346abc-ce1c-11e7-93e6-5ab1ba456173.jpg)

**Comment by sneakypete81** [comment]
@charlieseelig I didn't receive your email, can you please send it again?

Prioritising this, since it seems to be affecting a few people. In the meantime, you can use Firefox ESR (https://www.mozilla.org/en-US/firefox/organizations/) - this is currently Firefox 52, so will work with the previous version of Update Scanner. You can then install Update Scanner 3.3.2 from https://addons.mozilla.org/en-US/firefox/addon/update-scanner/versions/.

**Comment by sneakypete81** [comment]
I think I've found a problem with the import code. Sorry about this, and thanks for your patience.

Please check whether v4.0.1beta2 fixes this for you (available from the [Beta page](https://addons.mozilla.org/en-US/firefox/addon/update-scanner/versions/beta)).

**Comment by sneakypete81** [comment]
There's not yet any way of easily deleting all of your pages, so you might need to test this in a new Firefox profile.

**Comment by Daniel-at-github** [comment]
Workaround:

(Right click) updatescanner icon => (Contextual menu) Pin to overflow menu

In the `overflow menu` the presentation is OK (at least for me).

**Comment by sneakypete81** [comment]
@Daniel-at-github please check with 4.0.1beta2. If there's still a problem, please let me know.

**Comment by charlieseelig** [comment]
The update appears to be working. I did notice a) there used to be a status message at the bottom of the sidebar indicating which page was being scanned at that moment during the update. That no longer appears so it is a little more difficult to determine where the scanner is in its update.

And, the number of pages that the scanner shows has been updated was reduced significantly. That may be a result of the change to the new version and is temporary. We'll see how things go the next time I run it.

**Comment by sneakypete81** [comment]
Thanks @charlieseelig, good to hear that the import is now working.

Scan progress indication isn't implemented yet - see #124.

**Comment by LRDI** [comment]
The beta2 has some positive effects - it emboldens the folder titles as well as the content, but the problem remains that the update caused us to lose all our Update Scanner pages. We still have them all saved within Firefox bookmarks, but I can see no way to transfer those bookmarks directly to Scanner in one go. The only option at the minute seems to be to open each bookmark from Firefox invididually and add back to scanner manually, which could take a full day.

**Comment by sneakypete81** [comment]
@LRDI - [Create a new Firefox profile](https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles), install v4.0.1beta2, then import your pages as you did last time. Please let me know if it imports correctly.

I'm working on #117 at the moment, which will provide a better way of restoring your pages from .JSON format. Thanks for your patience.

**Comment by LRDI** [comment]
I went with the suggestion of going back to the old version of firefox and the old version of Scanner - this has thankfully worked and all the old scanner bookmarks are restored. Hopefully this is sustainable. Thanks. @Mirelore1 if you haven't already resolved your issue this may be the solution.

**Comment by Mirelore1** [comment]
@LRDI - For me v4.0.1beta2 fixed the problem, I removed the old version then I installed v4.0.1beta2 and I imported again the .json file and now is ok. I'm using it in sidebar. Thank you so much @sneakypete81
