### ISSUE TITLE
Blocked by Content Security Policy

### ISSUE THREAD

**Issue by Keith94** [sneakypete81/updatescanner#140]
I added some github.com pages to update scanner, but trying to view the new changes gives me this error.

>Blocked by Content Security Policy
>This page has a content security policy that prevents it from being loaded in this way.
>Nightly prevented this page from loading in this way because the page has a content security policy that disallows it.

![image](https://user-images.githubusercontent.com/5490615/32988068-a689bec8-ccb0-11e7-938f-f4dd72b380e5.png)

**Comment by sneakypete81** [comment]
I don't see this problem when scanning this page (see below). Do you see this in Firefox 57 too? Please provide a URL for the page that's giving you trouble, along with exactly how to reproduce the problem. If it's only after clicking a link in the page, this is a known issue (#122)

<img width="1066" alt="screen shot 2017-11-19 at 14 33 26" src="https://user-images.githubusercontent.com/38854/32991619-bc04d16c-cd36-11e7-9f29-417576d1d77d.png">

**Comment by Keith94** [comment]
>If it's only after clicking a link in the page, this is a known issue

It might be. If I'm viewing the changes of a github page (like your screenshot) and then click any link on that page, I get that CSP error. I only have Nightly installed btw.

**Comment by sneakypete81** [comment]
See #122
