### ISSUE TITLE
Add folder icons in sidebar

### ISSUE THREAD

**Issue by Keith94** [sneakypete81/updatescanner#142]
Similar to Firefox bookmark folders:
![image](https://user-images.githubusercontent.com/5490615/33042820-059838fc-cdf8-11e7-836c-9eb431e447d6.png)

**Comment by Keith94** [comment]
Also, show the favicons for pages in the sidebar, if possible.

**Comment by h-h-** [comment]
I also would like to see the favicons in the sidebar. Like in update scanner before FF57.

**Comment by sneakypete81** [comment]
Unfortunately I don't think Firefox provides an API for this anymore, so we need to find another way of downloading favicons.

**Comment by Keith94** [comment]
@sneakypete81 Please keep us updated if you find anything :D
