### ISSUE TITLE
manual scan

### ISSUE THREAD

**Issue by zelfr** [sneakypete81/updatescanner#144]
Hello, I would like to ask how I can manually scan my web pages for update scanner?

Thank you.

**Comment by sneakypete81** [comment]
Click the toolbar button -> Menu -> Scan All Pages.

It's not yet possible to scan individual pages or folders though - that feature is coming!

![image](https://user-images.githubusercontent.com/38854/33062911-b1039470-ce98-11e7-9edd-7b145c5b8a65.png)
