### ISSUE TITLE
Be able to select only certain parts of the page to be scanned

### ISSUE THREAD

**Issue by JBey4you** [sneakypete81/updatescanner#145]
Hello,

I saw that Update Scanner has recently been updated to support WebExtension, which is great. Although I was wondering if it is possible to implement a feature to only scan certain parts of the website and not the full page.

With Page Monitor on Chrome for example, you can select a specific part with your mouse and that’s it. It’s also the case with another Firefox addon (SiteDelta Watch). I am asking because Update Scanner seems to work better for me than SiteDelta Watch haha.

![capture d ecran 2017-11-21 a 04 33 53](https://user-images.githubusercontent.com/7979756/33053772-9b40a718-ce75-11e7-9511-82af44f8d8eb.jpg)
_Here with Page Monitor, I only selected the Google logo and not the entire page_

Thanks!

**Comment by sneakypete81** [comment]
See #50
