### ISSUE TITLE
Old Update Scanner bookmarks not scanning

### ISSUE THREAD

**Issue by LRDI** [sneakypete81/updatescanner#147]
Since the update to the latest version of Firefox and Scanner 4.0  number of things have gone wrong. Initially the last few hundred of our bookmarks were replaced by "New page" but since then none of our bookmarks under "Update Scanner's Pages" (see halfway down sidebar in screen grab) are being scanned. The only thing we can get to scan are bookmarks we've added manually since the update. Is there a way to get our old bookmarks scanning again without adding them all manually again, because we were scanning about a thousand bookmarks and obviously adding them all again manually will take a very long time.
![image](https://user-images.githubusercontent.com/33873249/33083618-c1787cc8-ced7-11e7-9d43-9c88cd126b22.png)
Thanks

**Comment by sneakypete81** [comment]
See #139. Please let me know whether 4.0.1beta2 fixes this for you.
