### ISSUE TITLE
Option to add a new page missing from right-click menu

### ISSUE THREAD

**Issue by ipswitch8** [sneakypete81/updatescanner#150]
Option to add a new page missing from right-click menu.
Manually adding a bookmark to the appropriate folder in the bookmarks doesn't work either.  (Bookmark is added but Update Scanner does not "see" it, but maybe that was always the case?  Possible enhancement?).

_(Note: using the icon in the toolbar to add a page **does** work, this is a minor bug report.)_

 * Firefox version: 57
 * Update Scanner version: 4.0.0

#### Steps to reproduce the problem:
right-click on a page to be scanned

#### What you expected to happen:
be able to click option to add the page to the scanning list

#### What actually happened:
option to add is missing

**Comment by sneakypete81** [comment]
This isn't supported anymore - instead click the toolbar icon and then the "New" button.

Regarding your bookmarks question, unfortunately Firefox no longer provides a full bookmarks API to addons, so the Update Scanner page list is now stored separately from your bookmarks.
