### ISSUE TITLE
"Show all updates"-menu disappears when there are too many sites in the list

### ISSUE THREAD

**Issue by studioart** [sneakypete81/updatescanner#151]
Hi,

I have a lot of sites within the UpdateScanner list.
Today I got 34 updates, but the list is too long and there is no scroll bar, to scroll to the end of the list to click "show all updates". So no chance to open all these updates in separate tabs with just one click.

See here the full list without seeing the "show all updates" button:
https://www.dropbox.com/s/lpjldy7jxaul2vl/updatescanner.jpg

This menu is at the bottom of the list:
https://www.dropbox.com/s/bzemura1k5vyc66/updatescanner2.jpg
and you can only see it, if the list of updated sites is not too long.

**A scroll bar would be great for this list of updated sites, or adding this menu on top of the list instead at the bottom of it.**

 * Firefox version: 57.0 32bit
* Windows 7 prof.
 * Update Scanner version: 4.0.0

**Comment by sneakypete81** [comment]
See #138. This is fixed in the latest beta, available on the [Beta page](https://addons.mozilla.org/en-US/firefox/addon/update-scanner/versions/beta).
