### ISSUE TITLE
Scanned Pages wont show videos 

### ISSUE THREAD

**Issue by hhayf** [sneakypete81/updatescanner#152]
To help explain the issue, please include the following:
 * Firefox version: 57
 * Update Scanner version: 4.0.0

#### Steps to reproduce the problem:
http://www.surrenderat20.net/2017/11/the-hunt-project-hunters-animated.html
and every page with videos

#### What actually happened:
Pages that include videos show a black box in their place.

**Comment by sneakypete81** [comment]
When viewing changes, the page is loaded into a secure sandbox. This means video plugins are disabled.

To see the video, click on the title in the header to load the "real" page, and play the video from there.
