### ISSUE TITLE
Sometimes,scanned pages wont open on click

### ISSUE THREAD

**Issue by hhayf** [sneakypete81/updatescanner#153]
To help explain the issue, please include the following:
 * Firefox version: 57
 * Update Scanner version: 4..0.0

#### Steps to reproduce the problem:
https://worldofwarcraft.com/en-gb/news

#### What actually happened:
In the above page,when I click on a Hotfix post in the scanned page,it will return a blank white page instead of the proper page.I have found similar behaviour in  other pages but I cant recall anything right now.

**Comment by sneakypete81** [comment]
See #122.
