### ISSUE TITLE
4 Removes Ability to Click Links Featured in Page Entries

### ISSUE THREAD

**Issue by aurumastrum** [sneakypete81/updatescanner#157]
I use Update Scanner for auction listings, so if new results popped up, I would usually click on each listing and be redirected to the actual URL of the auction listing.

With the new Firefox update, Update Scanner was also upgraded. I ran into some trouble when I noticed that clicking on an auction listing pulled up a blank page instead, and I haven't been able to find a workaround in the interface.

Here is the URL of the scanned page entry in Update Scanner-
moz-extension://c2631a0e-0ec3-4a1a-a771-c77e184b12ba/app/main/main.html?action=show_diff&id=45

When clicking on a link on the page, it will keep the same URL, only the page will show up blank-
moz-extension://c2631a0e-0ec3-4a1a-a771-c77e184b12ba/app/main/main.html?action=show_diff&id=45
4 removes ability to click new links within scanned pages.

* Firefox version: 57
* Update Scanner version: 4
* OS: Windows 10

#### Steps to reproduce the problem:
Went to updated page entries listed in the sidebar, and clicked the links shown on the page.

#### What you expected to happen:
I would arrive at the new link, as I would in previous versions.

#### What actually happened:
The page becomes blank and retains the URL of the Update Scanner page entry.

Thank you so much! I love this app, and hope I can continue using it. :)

**Comment by sneakypete81** [comment]
See #122

**Comment by aurumastrum** [comment]
Thank you! I did not realize that thread and mine were about the same thing. :)
