### ISSUE TITLE
Win7: All sidebar items marked in bold.

### ISSUE THREAD

**Issue by jamiemarsters** [sneakypete81/updatescanner#158]
I haven't seen anyone else mention this issue, so it may just be me (which, if it is, I have NO idea why), but ever since the Firefox 57 update, and all subsequent Update Scanner updates (including the latest 4.1.0), everything in my sidebar has been bold & has remained bold no matter what (whether a page has been updated or not, or I've clicked on an updated page or not).

The only way I'm currently able to tell if a page has actually been updated is via the new drop-down list of updates (which I LOVE btw, thanks so much!). But I like being able to check at a glance on my sidebar to see what's updated, how many pages have been updated & to actually click through to updated pages from the sidebar, so it's kinda irritating that everything is always bold.

I've attached some screenshots as well. As you can see in the second screenshot, I've clicked on to an 'updated' page (there weren't actually any changes, so it shouldn't have been bold to begin with), and it's still showing in bold after I've clicked
![image1](https://user-images.githubusercontent.com/34014151/33247885-86fd29b6-d375-11e7-99d9-6c7e87a41959.png)
![image2](https://user-images.githubusercontent.com/34014151/33247888-8b9648cc-d375-11e7-860b-be024673655d.png)

.

**Comment by sneakypete81** [comment]
Which OS are you using?

It might be a custom theme or another addon that is affecting this - please try with a [clean Firefox profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) .

**Comment by jamiemarsters** [comment]
I'm using Windows 7. I've tried a clean profile, then I tried disabling all add-ons bar Update Scanner as well, & no change.

And I've only ever used Firefox's default theme.

**Comment by jamiemarsters** [comment]
Just to let you know, I've also tried completely uninstalling the add-on, then reinstalling & that didn't make a difference either.

**Comment by einst3** [comment]
please give a link url and its settings so we can check it out. for feeds large changes occur frequently so upping the characters might help, also turn off changes to numbers. 
make sure the url is correct sometimes its a https vs http url or an ending backslash / on links that cause them to turn on.
i keep a bookmark folder with the same urls i use in updatescanner so when i click the page for update i know if it does not show as bookmarked i know the url changed. also some urls redirect like https://www.mozilla.org/en-US/firefox/notes/ to the current release url so those i set to a larger check time since it will always show as changed.

**Comment by kennioje** [comment]
I have this too - it's not just you!

It is clear that Update Scanner knows correctly whether a page has updates or not, as they only appear on the Taskbar Pulldown menu when they do have updates, and disapear from there when they have been viewed. It is just in the sidebar that they are always bold (though 'dead' links are showing correctly greyed).

Is there a chance this is a 32bit vs 64bit Firefox issue?

Update Scanner 4.2.0
Firefox 58.0.2 (64-bit)
Windows 7

**Comment by jamiemarsters** [comment]
Well, I'm also 64-bit, so you could be on to something! Is there anyone with the 64-bit Firefox who's *not* having this issue? (Also with Windows 7, as the combo may be contributing).

And all of the above is exactly the same for me, including the dead links being correctly shown as greyed out. Nice to know it's not just me!

**Comment by yermulnik** [comment]
> Is there anyone with the 64-bit Firefox who's not having this issue?

I'm not having:
```
$> uname -srm
Linux 4.4.0-116-generic x86_64
$> dpkg -s firefox | egrep "^(Architecture|Version)"
Architecture: amd64
Version: 58.0.2+linuxmint1+rosa
```

**Comment by sneakypete81** [comment]
I think this is most likely only affects Windows 7.
A few things you can try:
 * Change the various Firefox font settings
 * Change the zoom level in the sidebar (hover the mouse over the sidebar, hold down CTRL and turn the mouse scroll wheel)
 * Disable hardware acceleration (see https://support.mozilla.org/en-US/kb/troubleshoot-extensions-themes-to-fix-problems)

**Comment by jamiemarsters** [comment]
Nope, tried all of the above & no change.

**Comment by sneakypete81** [comment]
Ok, thanks. It's not clear why this only affects WIn7.
This will probably require some kind of CSS workaround in app/sidebar/jstree_theme/style.css or app/sidebar/sidebar.css

**Comment by molitar** [comment]
I have the same problem with Windows 7 x64.

**Comment by einst3** [comment]
funny the greyed items in my sidebar include update scanner on firefox
https://addons.mozilla.org/en-US/firefox/addon/update-scanner/versions/

**Comment by molitar** [comment]
Any update on this bug?  It's really difficult to use when everything is bold showing updated.

**Comment by molitar** [comment]
sneakypete81, found the answer to this problem from another thread located at https://github.com/piroor/treestyletab/issues/1379.  

> It seems firefox use the font setting of 'window title' as default for the setting page and sidebar.
> After set font weight of 'window title' from bold to normal in control panel, every thing back
> to normal.

Now are you able to change this in the extension not to read the settings from Windows Inactive Titlebar or overide it from being Inactive Bold to non bold?  

Seems Windows 7 makes Inactive Title Bars bold also.

**Comment by sneakypete81** [comment]
Thanks @molitar, We could try overriding the default Firefox font to be "message-box" for the sidebar content. We currently use whatever is specified in Firefox's default extension.css ("dialog").

To test this, please try the following:
* Click on any item in the sidebar to open it in the main window pane.
* In the URL bar, replace the text "/app/main/main.html?action=show_diff&id=nn" with "/app/sidebar/sidebar.html". This should show the sidebar contents in the main window.
* From the Firefox menu, open the "Web Developer"->"Inspector" pane (or press CTRL-Shift-C).
* Click the "&lt;body&gt;" element in the left pane.
* In the other pane, change "font: caption" to "font: message-box"

Does that help? If not, try adding a new item to the list: "font-weight: normal".

**Comment by molitar** [comment]
Hi Sneakypete81, that worked changing to font:message-box

**Comment by sneakypete81** [comment]
That's good news, thanks for confirming.

On reflection, I'll try the `font-weight: normal` modification instead, since this is a clearer indication of what we're trying to achieve.

https://github.com/mozilla/web-ext/pull/1353 is currently blocking signing of this add-on. I'm not sure when we'll have a beta signed and ready for testing.

**Comment by molitar** [comment]
Sneakypete81, are you able to tell how to edit the font-weight myself.  What file it needs to be added to?  I can at least try myself thanks

**Comment by molitar** [comment]
Hey sneakypete81, I tried that sidebar.css change and it is working good here.  So looks like that fixed the problem.

**Comment by sneakypete81** [comment]
Great, thanks. Please try 4.3.1beta2 (see #36 for details).

**Comment by jamiemarsters** [comment]
FYI This issue appears to have been fixed as of Tuesday (Aussie time). Sidebar is now correctly showing bolded updated items only. Thanks!
