### ISSUE TITLE
Notification Windows Options Were Removed? 

### ISSUE THREAD

**Issue by bahnbino** [sneakypete81/updatescanner#161]
I do not see any Notification box options in Firefox Quantum Update/ Scanner Version 4.0.1beta2. There used to be a way to make the notification box stay on-screen until you clicked it to open the tabs. Also, if the box could be smaller, like it used to be, that'd be even better.

**Comment by sneakypete81** [comment]
This is limited by the WebExtension notification API provided by Firefox. The previous method isn't supported by Firefox 57+, unfortunately.
Please raise a bug at http://bugzilla.mozilla.org/ to extend the API.
