### ISSUE TITLE
Google Sheet Changes not allowing Scrolling Down

### ISSUE THREAD

**Issue by stanhopper** [sneakypete81/updatescanner#162]
I could not readily see this bug. It was working in past FF versions.
Using FF 57.0
Using Scanner 4.1.0
In a shared Google Sheets worksheet, changes are presented only for the upper part of the worksheet. I cannot scroll down to view the additional changes at the bottom of the worksheet. 
In previous FF versions, this scrolling was possible. 
Maybe this has already been identified and with time it will be fixed.
Thanks

**Comment by sneakypete81** [comment]
Please provide a URL that shows the problem. I suspect Google Sheets might require Javascript to display properly.

**Comment by stanhopper** [comment]
URL provided...
moz-extension://8022b21b-2988-43c7-82d7-b11803b7b997/app/main/main.html?action=show_diff&id=33

**Comment by sneakypete81** [comment]
@stanhopper I meant the URL of the Google Sheets page

**Comment by stanhopper** [comment]
You can now delete this issue. I'm no longer using Update Scanner.
