### ISSUE TITLE
Popup and sidebar don't always identify updated pages

### ISSUE THREAD

**Issue by exposixtyseven** [sneakypete81/updatescanner#163]
Hi - 
Update Scanner was working great on Firefox 56 but it hasn't been performing the same in 57. I'm using the latest version of the scanner and the main problem is it's not showing many of the updated pages in bold nor in the box where the list of updated sites should appear. It works for some pages, but doesn't seem to work for all. My colleague also uses the scanner for the same pages and and she is being notified of updates that I am not getting.
Thanks,
Steve

**Comment by sneakypete81** [comment]
Please check the scan settings: how often the site is scanned, the scan threshold and whether numbers are ignored. You can test this on a page that updates regularly (http://whattimeisit.com/ is a good one).

**Comment by exposixtyseven** [comment]
Thanks for getting back to me. The settings all look fine. Today is a good example of what's going on - I received notification of 13 updates, but none were bolded and none appeared in the updates box...

**Comment by sneakypete81** [comment]
I can't reproduce this problem.

Is it always the same pages that you're having trouble with? If so, can you post the URL and your page settings?

Can you please try creating a new profile, installing Update Scanner, then testing with the URL I posted previously (this page updates itself continuously, so is useful for checking this kind of problem).

**Comment by exposixtyseven** [comment]
Hi –
Thanks for getting back to me. It’s working better these days. Still not spot on, but better. I’ll test that URL you posted and let you know.
Thanks,
Steve

**Comment by sneakypete81** [comment]
What are your page scan settings? Try setting the change threshold to the lowest possible, and make sure "Ignore changes to numbers" is unchecked.

**Comment by sneakypete81** [comment]
Please update this if you have any further information, perhaps this was a problem with your page scan settings.
