### ISSUE TITLE
Page with Cookie confirmation overlay is not updated

### ISSUE THREAD

**Issue by pietsukkel** [sneakypete81/updatescanner#164]
Hi Pete!
Ever since the UpdateScanner is updated it cannot handle a page with a Cookie confirmation overlay. For instance page http://tweakers.net/meuktracker presents such an confirmation. When UpdateScanner scans this page it shows this confirmation, but since the Accept button is no longer working within UpdateScanner, you cannot accept and thus you cannot remove the overlay.

Firefox version: 57.0
Update Scanner version: 4.1

Thanks for your help and keep up the very good work!
Piet

**Comment by sneakypete81** [comment]
This isn't very easy, unfortunately. See #119.
