### ISSUE TITLE
Scan list has disappeared

### ISSUE THREAD

**Issue by Barry64** [sneakypete81/updatescanner#165]
* Firefox version: 57.0 and now 57.0.1 (both 32 bit)
 * Update Scanner version: 4.1.0

Update Scanner was working for days.  Now, under Update Scanner, in the sidebar, it says "Can't see your scan list?  Upgrade to Upgrade Scanner 4."  Suspected cause:  my PC crashed about 3 times while Firefox was open.

The folder "Update Scanner's Pages" still exists in the bookmarks, with a list of the pages I've been scanning, although a couple of new pages I added are missing.

Disabling and reenabling, and deleting and reinstalling Update Scanner don't help.

Problem occurred in Firefox 57.0, and is still present in 57.0.1.

**Comment by Barry64** [comment]
I now see that at least a couple of new pages are missing from the Update Scanner's Pages bookmarks folder.  They were for the official Mozilla pages for some Firefox extensions.

**Comment by Barry64** [comment]
I also recall that my computer crashed a few times today with Firefox open, before I noticed the problem.

**Comment by Barry64** [comment]
I also recall that my computer crashed a few times today with Firefox open, before I noticed the problem.

**Comment by sneakypete81** [comment]
It's a concern that a Firefox crash could cause this problem. See #149.
