### ISSUE TITLE
Save Update Page Links in Bookmarks - like before

### ISSUE THREAD

**Issue by kaktux** [sneakypete81/updatescanner#171]
In the old version - before FF57 the pages to scan were saved like bookmarks: a "Update Page Scanner" Folder was created in the bookmarks and there the pages could be seen. 
Which was perfect as a bookmark sync/backup also included these. Along with the addon sync it was easy to use the Extension on several Computers.

Now i saw that it is available - and it does no longer include my main reason for usage: easy sync+backup alongside the bookmarks.
An extra sidebar for each extension on the other hand is a big step back in my opinion .

Would be great if this could be included again - as this would be the reason to switch back and an extra the other extensions scanning for updated pages don't include.

This is possible with my save-to-read replacement (pile) to - so scanning for updated pages is the only bookmark-like links that are not synced. So hopefully it is also possible with this.

This would be a great enhancement.

**Comment by sneakypete81** [comment]
> In the old version - before FF57 the pages to scan were saved like bookmarks...

Unfortunately the new Firefox WebExtensions API doesn't allow access to bookmarks annotations, so we've had to store the pages separately.

>...no longer include my main reason for usage: easy sync+backup alongside the bookmarks.

You can now backup and restore your pages in the menu from the Update Scanner toolbar icon.

> An extra sidebar for each extension on the other hand is a big step back in my opinion.

This is how sidebars are implemented in Firefox - again, not much we can do about this.
