### ISSUE TITLE
Better UX when adding new page

### ISSUE THREAD

**Issue by Keith94** [sneakypete81/updatescanner#172]
When you add a new page through Update Scanner, you are greeted with only a blank page saying "this page has not yet been scanned." There's no option to manually scan and no page content is displayed...IMO I don't find such a page very helpful to the user.

Instead, maybe the tab should be closed automatically and you can display a notification in the bottom corner saying "Page has been added!" or something to give better feedback. WDYT?

**Comment by sneakypete81** [comment]
Good feedback, thanks. Another option would be to immediately scan the page and show the result once complete.

Either way, I agree that the UX needs improving.

**Comment by btanner2** [comment]
100% agree to Keith94. Right now all sites have to be scannend to get rid of "this page has not yet been scanned". :)
