### ISSUE TITLE
Page returns error when scanned

### ISSUE THREAD

**Issue by Keith94** [sneakypete81/updatescanner#173]
* Firefox version: 59.0a1
 * Update Scanner version: 4.2.0

#### Steps to reproduce the problem:
Add https://www.reddit.com/user/Methanhydrat/

#### What you expected to happen:
Page can be scanned

#### What actually happened:
Page is grayed out in sidebar and returns an error

![image](https://user-images.githubusercontent.com/5490615/33555622-f4240d9e-d8b5-11e7-8adb-af64ec1f6c54.png)

**Comment by sneakypete81** [comment]
It's working for me:
![image](https://user-images.githubusercontent.com/38854/37555059-9fc17f14-29d9-11e8-9349-58d393695732.png)

Please check this again, is the URL entered correctly?
