### ISSUE TITLE
All Bookmarks of UpdateScanner have disappeared

### ISSUE THREAD

**Issue by studioart** [sneakypete81/updatescanner#176]
Hi,

today I wondered why I don't get any updates from Update Scanner anymore; then I looked at the Update Scanner sidebar - and there are no bookmarks at all.

**I already checked these issues:**

- https://github.com/sneakypete81/updatescanner/issues/149
but a new FF profiles has not helped, and I have already installed the Beta 1 of UpdateScanner

- https://github.com/sneakypete81/updatescanner/issues/165
FF has not crashed in my case

I don't know the exact point of time since this list has disappeared, maybe with FF update 57.0.1, which I got these days.

- Why has this list been deleted, how to avoid this and how to get it back please?**
- where are the new added bookmarks within the UpdateScanner menu stored? In the older version of this AddOn I could see them in a folder "Update Scanner Pages" in the bookmarks menu of Firefox, but there are only the older ones from the old AddOn version. 

 * Firefox version: 57.0.1 32bit
 * Update Scanner version: 4.2.0beta1

**Comment by sneakypete81** [comment]
Thanks for reporting, this is tracked in #149.
