### ISSUE TITLE
Each time Firefox crashes, then the complete UpdateScanner list is empty

### ISSUE THREAD

**Issue by studioart** [sneakypete81/updatescanner#177]
Hi,

each time, Firefox crashes (when I have too much tabs open for example), then the complete UpdateScanner list is empty.

 * Firefox version: 57.0.2  x32
 * Windows 7 prof. x64
 * Update Scanner version: 4.2.0beta1

#### Steps to reproduce the problem:
Firefox crashes, probably when too many tabs are open or what ever, then when I look at the UpdateScanner sidebar it is empty and all listed sites are gone.

**Comment by sneakypete81** [comment]
See #149
