### ISSUE TITLE
Popup UI issue with large number of items and/or overflow menu

### ISSUE THREAD

**Issue by Keith94** [sneakypete81/updatescanner#178]
The buttons at the bottom of the panel are displayed half gray/half white.

![2017-12-11_16-27-05](https://user-images.githubusercontent.com/5490615/33861023-6d2639ee-de90-11e7-9016-417790f7c6f8.png)

**Comment by StoyanDimitrov** [comment]
And the pop-up does not occupy the whole width of the overflow menu.

**Comment by einst3** [comment]
i have a large number of links so i usually open the side panel to show all links. otherwise you have to click and go back and forth (cumbersome).

**Comment by drumsibumsi** [comment]
This is how I see it. I have many links in the list.

![update-scanner](https://user-images.githubusercontent.com/2128661/38480246-15de44de-3bcd-11e8-9060-afd6688ad47b.png)

**Comment by sneakypete81** [comment]
I'll need to raise a Bugzilla to report this to Firefox, ideally with a cut down example

**Comment by molitar** [comment]
Yeah it seems limit is around 15 and then this bug happens.

**Comment by sneakypete81** [comment]
The display problem when in the overflow menu is tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1373490
