### ISSUE TITLE
www.opennet.ru

### ISSUE THREAD

**Issue by jt3k** [sneakypete81/updatescanner#179]
Thanks for creating a new issue!

Before continuing, please use the search box in the header above to check if someone has already reported it.

To help explain the issue, please include the following:
 * Firefox version: 57.0.1 (64-бит)
 * Update Scanner version:  I do not know where to look. but the latest version (13.12.2017)

#### Steps to reproduce the problem:
www.opennet.ru

#### What you expected to happen:
![](https://i.imgur.com/6rabh1f.png)
I expected that I would not receive rhombuses instead of cyrilic letters

#### What actually happened:
![Include a screenshot](https://i.imgur.com/lilya89.png)
I expect to receive cyrillic letters

**Comment by yermulnik** [comment]
https://github.com/sneakypete81/updatescanner/issues/136
