### ISSUE TITLE
Notifications no longer come up on the bottom right of my screen

### ISSUE THREAD

**Issue by kap15** [sneakypete81/updatescanner#180]
On the latest version I no longer see a notification come up on the bottom of my screen every time there is an update. Can we get that feature back?

**Comment by WHRoeder1** [comment]
Working fine 4.2.0/FF 57.0.2 for me.

**Comment by roooots** [comment]
Same problem here: No notification bubbles with 4.2.0 and 57.0.4.

**Comment by roooots** [comment]
Um...what's interesting: When I "Scan All Pages" using the menu, after 1..2 minutes a notification bubble "No updates were detected" appears in the top right screen corner. However, still no notification if changes have been detected. 

The time before the notification appears seems to be a bit long as well - I have ~20 entries for update scanner, with the addon it took just a few seconds to scan all pages.

**Comment by roooots** [comment]
Ok, gotta revert a bit...in fact I do get a notification bubble in the top right screen corner, but with a pretty long delay of some minutes after the update scanner icon in the FF bar shows me that there are N updates.
Maybe this partially goes along with #191 ?!

**Comment by sneakypete81** [comment]
@kap15 @roooots : What is your OS?

Update Scanner now uses the official Firefox notifications API, which seems to have different behaviour depending on the OS.

**Comment by roooots** [comment]
Hi,
Ubuntu 16.04.4 with gnome-classic / gnome-panel here.

**Comment by sneakypete81** [comment]
>  but with a pretty long delay of some minutes after the update scanner icon in the FF bar shows me that there are N updates.

The badge on the icon updates as the scan is taking place, but the notification popup isn't displayed until the scan is complete. That might explain the delay you're experiencing.

#124 should help improve the UX for this.
