### ISSUE TITLE
Feature request: sort by name

### ISSUE THREAD

**Issue by jfg001** [sneakypete81/updatescanner#192]
hello,
in version 3, there was: sort by name. with a right click on the folder.
This is a very important function and I will want to know if you are going to implement it.
For now, I stay at firefox 56 and updatescanner 3
Best regards
JF

**Comment by SaintJason** [comment]
Seconded. 
I use US to track government sites for my clients, being able to sort them when I add new ones (and see if I've added a copy) is immensely valuable.

**Comment by btanner2** [comment]
+1

**Comment by sneakypete81** [comment]
see #143
