### ISSUE TITLE
Error at https://twitter.com/spacex

### ISSUE THREAD

**Issue by auv-ee** [sneakypete81/updatescanner#195]
To help explain the issue, please include the following:
 * Firefox version: 57.0.4 (64-bit) Linux
 * Update Scanner version: 4.2.0

#### Steps to reproduce the problem:
enter https://twitter.com/spacex as a target to test for updates.

#### What you expected to happen:
To be notified of changes to the target page.

#### What actually happened:
Receive this error:
![update_scanner_spacex_error](https://user-images.githubusercontent.com/35354093/34855438-ba3112f0-f70d-11e7-9be8-36f1290f8607.png)

and the target in the side pane remains greyed out.  If I click on the "title above to see what's wrong", the page displays correctly, so there is no evidence of "what's wrong".

All my other target pages appear to work as expected.

**Comment by sneakypete81** [comment]
It's working for me:
![image](https://user-images.githubusercontent.com/38854/37555159-206cf8ea-29db-11e8-8f41-2cbb3365cfc9.png)

Could you please check that you have the correct URL?

**Comment by auv-ee** [comment]
On 03/17/2018 08:03 AM, sneakypete81 wrote:
> It's working for me:
> ![image](https://user-images.githubusercontent.com/38854/37555159-206cf8ea-29db-11e8-8f41-2cbb3365cfc9.png)
> 
> Could you please check that you have the correct URL?
> 

try:

https://twitter.com/spacex

Does NOT work with update scanner.

What URL did you use?

-- 
Ned Forrester                                    nforrester@verizon.net
