### ISSUE TITLE
wDiffRecursiveDiff declared in /lib/diff/diff_engine.js but _wDiffRecursiveDiff used

### ISSUE THREAD

**Issue by kolonist** [sneakypete81/updatescanner#203]
On line 116 in file `/lib/diff/diff_engine.js` you declare `wDiffRecursiveDiff`:

```javascript
wDiffRecursiveDiff : true,
```

but when you use in on lines 394 and 438, you write

```javascript
 if (me._wDiffRecursiveDiff) {
```

Note prepending underscore.

**Comment by sneakypete81** [comment]
Interesting, thanks!
The engine gives good results without RecursiveDiff enabled, so I propose fixing this typo and setting it to false.
