### ISSUE TITLE
Feature Request: Export list

### ISSUE THREAD

**Issue by SaintJason** [sneakypete81/updatescanner#206]
Hello,

I'd like to request a way to export our list of US sites. You could export the bookmarks back with US2, but there is no way to do this with 3. (that I can find).

Ultimately, I'd like to be able to answer my boss when he says "well, what sites are you tracking for us".

**Comment by yermulnik** [comment]
`Updatescanner icon → Menu → Backup Pages`?

**Comment by SaintJason** [comment]
...gives a bad .json file that Firefox can't read.

**Comment by sneakypete81** [comment]
Do you mean that the JSON file is corrupt, or that you can't import it into Firefox bookmarks system?

Update Scanner no longer stores it's pages as bookmarks, and importing them as bookmarks won't work. You can still open the JSON file in Firefox (ctrl-o then select the JSON file) to get a browseable view of your exported pages.
