### ISSUE TITLE
Deleted list after Firefox crash

### ISSUE THREAD

**Issue by studioart** [sneakypete81/updatescanner#214]
Hi,

every time Firefox is crashing, the complete Update Scanner list is deleted!
I need to restore them from a former backup; as I do not know, when Firefox crashes again, I need to backup the list every time I add something new to it :-(

How to fix this, so that the list (in the sidebar) remains, even if Firefox crashes?
Thanks.

 * Firefox version: 58.0.2
 * Update Scanner version: 4.2.0
*  Screenshot of the sidebar after a Firefox crash: https://imgur.com/oMcsPiO

Even this warning is not right: I DO have 4.2.0 installed!

**Comment by sneakypete81** [comment]
Tracked in #149
