### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by ZamotZ** [sneakypete81/updatescanner#216]
When starting the Scan (of ~15 pages), Firefox is starting to increase memory usage (>5GB).
This is reproducible with my configuration. Unfortunately, I found no log-files to attach.

Any debug-versions I can install? Or log-files I can attach?

**Comment by yermulnik** [comment]
Same here #184

**Comment by dade-shinji** [comment]
Same here...Firefox becomes almost unusable because it becomes very very very slow. All this disappear when the scan ends.

**Comment by AJCxZ0** [comment]
Same here. When scanning Firefox sometimes consumes a very large amount of memory, sometimes causing the firefox process to be killed.

Reproduced a moment ago while reproducing [Issue 218](https://github.com/sneakypete81/updatescanner/issues/218) and managed to grab a quick `top` snapshot:
```top - 14:51:40 up 5 days, 15:57,  8 users,  load average: 26.24, 20.86, 10.83
Tasks: 356 total,   6 running, 346 sleeping,   0 stopped,   4 zombie
%Cpu(s):  1.9 us,  0.6 sy, 95.6 ni,  1.9 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 16431156 total,   152420 free, 15793892 used,   484844 buff/cache
KiB Swap:        0 total,        0 free,        0 used.    71252 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
29125 ajc       20   0 10.849g 8.351g  24400 D   0.7 53.3  24:40.02 firefox
 8518 ajc       20   0 4469356 1.734g      0 D   0.7 11.1  50:47.38 chromium-b+
 6916 ajc       20   0 2816740 952508 116916 D   0.0  5.8 101:08.14 compiz
```

**Comment by Hiltronix** [comment]
This addon has become unusable for me.  There is a memory leak that consumes all memory and drags my computer to a halt.  It used be my fav addon.

**Comment by sneakypete81** [comment]
Tracked in #191
