### ISSUE TITLE
Updates highlighted, but not showing in bold in Update Scanner

### ISSUE THREAD

**Issue by exposixtyseven** [sneakypete81/updatescanner#220]
Thanks for creating a new issue!

Before continuing, please use the search box in the header above to check if someone has already reported it.

To help explain the issue, please include the following:
 * Firefox version: 59.0
 * Update Scanner version: Latest...

#### What you expected to happen:

Update should appear in **bold** in my scanner, but it didn't. The changes were highlighted on the page, however, so there's some disconnect here.

#### What actually happened:
![scanner](https://user-images.githubusercontent.com/33962191/37420844-28ccacfa-278e-11e8-8c2a-6fff816ca08b.JPG)

**Comment by sneakypete81** [comment]
Tracked in #163, or is this a different issue?
