### ISSUE TITLE
Update Scanner Backup to classic bookmarks.json

### ISSUE THREAD

**Issue by jfg001** [sneakypete81/updatescanner#225]
hello
I would like to recover my "Update Scanner backup" to install it on another computer in classic bookmarks (without Update Scanner).
Is it possible ? I can not import the file into firefox.
Thanks
jf

**Comment by sneakypete81** [comment]
The file formats are not compatible, unfortunately. Even if they were, using the Firefox "restore bookmarks" feature would overwrite all other bookmarks on the second computer.

**Comment by jfg001** [comment]
hello
can you then export to html? i saw with jsonviewer that there was everything in the file
