### ISSUE TITLE
Cyrilic Encoding trouble

### ISSUE THREAD

**Issue by neharon** [sneakypete81/updatescanner#226]
* Firefox version: 59.0.1 (64-bit)
 * Update Scanner version: 4.2.0

#### Steps to reproduce the problem:
add http://directlot.ru/products.php  to autoscan
and get wrong encoding page. Header is normal encoding, but page content is wrong. 
Screenshot:
https://yadi.sk/i/iZxs1zuI3TbatA

**Comment by sneakypete81** [comment]
See #136.
