### ISSUE TITLE
Firefox in Private Browsing show only blank pages

### ISSUE THREAD

**Issue by ppasserini** [sneakypete81/updatescanner#239]
==sorry, duplicate Issue. Please delete it.

Until the previous version, updatescanenr for working with Firefox in Private Browsing tab. With the latest version, instead, I'm getting only blank pages

 * OS version: Win 7 x64
 * Firefox version: 59.0.2 x64
 * Update Scanner version: 4.3.0

Thanks anyway for this amazing extension.

**Comment by sneakypete81** [comment]
Thanks, see #234
