### ISSUE TITLE
Enhancement request - show until manually closed

### ISSUE THREAD

**Issue by BloggerJen** [sneakypete81/updatescanner#247]
I would like to see the notification window options come back, specifically the show until manually closed. 
It's a great visual flag, because it's large, for when I've stepped away from the pc for a while and have returned.  

 * OS version:win7
 * Firefox version:59.0.3 (new is downloading now, will be 60)
 * Update Scanner version:4.3.0

#### What you expected to happen: pop up notification window will stay on top of firefox until manually closed instead of closing after a short time.

**Comment by sneakypete81** [comment]
Unfortunately I don't think this is possible with a WebExtension. We're using Firefox's official notification API.

You will need to check the red badge on the toolbar icon instead, although this isn't as big and obtrusive as the popup notification.
