### ISSUE TITLE
Tumblr pages - JavaScript is required to view this site. 

### ISSUE THREAD

**Issue by Mirelore1** [sneakypete81/updatescanner#250]
Thank you for this awesome add-on!
Since yesterday after scan on Tumblr pages this message is shown "JavaScript is required to view this site." and the real changes from this pages aren't highlighted (no bold text in sidebar for blog names with changes).
I use Update Scanner version 4.2.0, Firefox 60.0.1 and Windows 10 Pro
![image 2](https://user-images.githubusercontent.com/33838827/40281260-fc01b0bc-5c67-11e8-8250-15ed2494bb45.jpg)
![image 3](https://user-images.githubusercontent.com/33838827/40281261-fc1d8a08-5c67-11e8-876c-bbfe5ff12b06.jpg)

**Comment by sneakypete81** [comment]
Tumblr seems to load its content with Javascript. Update Scanner only scans raw HTML pages.

Unfortunately there's not much we can do if Tumblr don't support Javascript-less browsers.
