### ISSUE TITLE
Scanner not alerting to page updates on the tab

### ISSUE THREAD

**Issue by keybored13** [sneakypete81/updatescanner#259]
Had this problem the last few days now.

 * OS version: Windows 7
 * Firefox version:Firefox Quantum 60.0.2 64bit
 * Update Scanner version: 4.3.0

#### Steps to reproduce the problem:
Removed and added page again

#### What you expected to happen:
Tab to have alert showing a change on the page occured

#### What actually happened:
Nothing showing after update on the tab.

Thanks in advance.

**Comment by sneakypete81** [comment]
> **Steps to reproduce the problem:**
> Removed and added page again

Removing and adding a page doesn't trigger an alert, the page content needs to change.

If you're having a problem with a particular website, please post the URL and I'll take a look.

**Comment by keybored13** [comment]
The page had been updated but no sign of any updates were shown on the tab before or after I re-added the page.

Today however, there were 14 updates on the page which showed up on the tab, so for now it appears to be working again.

If it happens again I will let you know and which URL it was happening on.

Thanks.

**Comment by sneakypete81** [comment]
Thanks - closing for now.
