### ISSUE TITLE
Cleaning Offline website data disables updatescanner without warning

### ISSUE THREAD

**Issue by Daniel-at-github** [sneakypete81/updatescanner#267]
#### Steps to reproduce the problem:
* Configure _Offline website data_ to be cleaned every time Firefox is closed
* Restart Firefox

#### What you expected to happen:
(Fail, because it's my fault, but it will be nice if I could expect to)
Be warned that updatescanner will not work

#### What actually happened:
updatescanner got silently "deactivated"

**Comment by sneakypete81** [comment]
Is this the same as #235?

**Comment by Daniel-at-github** [comment]
I think so, It's just another way to clear Offline website data when closed.
