### ISSUE TITLE
Updatescanner 4.3.1beta2 New Bug bottom cut off

### ISSUE THREAD

**Issue by molitar** [sneakypete81/updatescanner#278]
Thanks for creating a new issue!

Before continuing, please use the search box in the header above to check if someone has already reported it.

To help explain the issue, please include the following:
 * OS version: Windows 7 Ultimate 64-bit
 * Firefox version: 62.0b
 * Update Scanner version: 4.3.1beta2

#### Steps to reproduce the problem:
Scanned and found new sites then clicked on button.  Bottom of the window is cut off unable to read the words Scan All, Add, and Sidebar.

#### What you expected to happen:
Bottom of window not to be cut off

#### What actually happened:
![bottom cut off](https://user-images.githubusercontent.com/16074561/44883989-777c5700-ac87-11e8-9352-24cc543d861b.png)

**Comment by sneakypete81** [comment]
This is covered by #178, I think.
