### ISSUE TITLE
Support Firefox for Android

### ISSUE THREAD

**Issue by DDoSolitary** [sneakypete81/updatescanner#279]
Firefox for Android doesn't provide sidebars so I can't manage the added pages. Also, the panel is displayed in a standalone page and is extremely small. Please make it fill the whole screen on Android.
Thanks!

**Comment by Riajyuu** [comment]
@DDoSolitary Hi
Glad to meet you here and here are some tips for developer:
- If you are to fit Android use, best ui build is full responsive design tough requires complete rewrite.
- use background service carefully, especially for such a addon with regular tasks cos you shouldn't dry out battery. (tough from this circumstances I don't think Android support is a good idea.)
- ui elements should be redesigned, especially on size and layout.

**Comment by sneakypete81** [comment]
Thanks for reporting, this addon isn't designed to be Android compatible. I'm not sure why the addons website is allowing it to be installed.

The UI would need a complete rethink, since there's no sidebar available.

**Comment by Riajyuu** [comment]
@sneakypete81 The reason is pretty simple: it is Firefox intended design. Only specific APIs used will be marked compatible. Otherwise it will be available on Android.

**Comment by DDoSolitary** [comment]
@Riajyuu However, this extension uses sidebar, which doesn't seem to be available on Android. Why is it still marked compatible?

**Comment by sneakypete81** [comment]
The add-on is marked as incompatible with Android. The problem is with the addons.mozilla.org website - see https://github.com/mozilla/addons-frontend/issues/6136.
