### ISSUE TITLE
Since upodate to 4.3.0 not working /only working some times

### ISSUE THREAD

**Issue by wombat33** [sneakypete81/updatescanner#280]
Hi,

since I upgraded to 4.3.0 update scanner is not working correctly anymore.
It worked greate with the previous version.
I tryed to reinstall it completely and restored my Pages, but they are only updated randomly (my impression) since.
Every time I restore at least one Page from previous backup, it works again. But if I close firefox, I have to start over again.
Am I doing s.th. wrong?

 * OS version:
Ubuntu Linux, 4.15.0-33-generic #36-Ubuntu, x86_64 x86_64 x86_64 GNU/Linux
 * Firefox version:
61.0.1 (64-Bit)
 * Update Scanner version:
4.3.0

#### Steps to reproduce the problem:
[Include webpage URL, if applicable]

#### What actually happened:
[Include a screenshot]

**Comment by Daniel-at-github** [comment]
Take a look at #235

**Comment by sneakypete81** [comment]
Please try to reproduce your problem in a fresh profile with no configuration changes or other addons installed (https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles).

**Comment by sneakypete81** [comment]
Closing, please indicate if you have further information on how to reproduce this problem.
