### ISSUE TITLE
Help me PLEASE. I can no longer SORT alpha my 1000 bookmarks. I use this daily for my work. Since the change over from the Firefox add-on I am totally lost. Also I am not that computer literate. Thank you !!

### ISSUE THREAD

**Issue by gdillon6** [sneakypete81/updatescanner#282]
Thanks for creating a new issue!

Before continuing, please use the search box in the header above to check if someone has already reported it.

To help explain the issue, please include the following:
 * OS version:
 * Firefox version:
 * Update Scanner version:

#### Steps to reproduce the problem:
[Include webpage URL, if applicable]

#### What actually happened:
[Include a screenshot]

**Comment by gdillon6** [comment]
PLEASE REPLY !

**Comment by sneakypete81** [comment]
Sorry for the delay in replying. This is #143.
The only way to achieve this at the moment would be to:
 * Export your pages
 * Read the resulting .JSON with a script, sort, write back out
 * Import the resulting file
You would lose your page change history, however, so it's not very useful.
