### ISSUE TITLE
Update scanner does not work in Tor browser

### ISSUE THREAD

**Issue by h-h-** [sneakypete81/updatescanner#283]
When using updatescanner in latest Tor browser 8.0 (based on Mozilla Firefox 60.2.0esr) (32-Bit) it doesn´t work. It shows that it scanned web pages but it shows neither differences nor old or new page contents

OS: Win7 pro 32 bit
Update Scanner version: 4.3.0
Downloaded Tor browser from https://www.torproject.org/projects/torbrowser.html.en#downloads - Deutsch 32/64-bit for Microsoft Windows

**Comment by sneakypete81** [comment]
I think you're probably right, closing this in favour of #234.
