### ISSUE TITLE
Error for pages like https://addons.mozilla.org/*

### ISSUE THREAD

**Issue by btanner2** [sneakypete81/updatescanner#285]
Hi,

I try to watch add on pages from Mozilla, to get notified if something changed, like:

https://addons.mozilla.org/de/firefox/addon/update-scanner/versions/

Unfortunately Update Scanner gives an error for such pages:

This page returned an error when scanned. Click the title above to see what’s going on.

Is there any reason for this?

Kind regards
Brian

**Comment by Gitoffthelawn** [comment]
To my knowledge, this actually isn't a bug.  Mozilla changed things up so that extensions cannot access AMO pages.  You can set some prefs to allow this.  If you're interested in those prefs, I can look them up and post here.

**Comment by sneakypete81** [comment]
Good catch, I see to remember reading something about that too. This is a security feature of Firefox, and I don't think it can be overridden without creating a potential security risk.
