### ISSUE TITLE
No yellow color for updated text? 

### ISSUE THREAD

**Issue by yolinfl** [sneakypete81/updatescanner#287]
I'm a big fan of Update Scanner, but recently I don't see changed text op pages in yellow color anymore.
Is there an option to change this? Am I doing something wrong? 
I'm using FF 62.0.2 and Update Scanner 4.3.0.
Thank you
Yolanda

**Comment by sneakypete81** [comment]
Please try to reproduce your problem in a fresh profile with no configuration changes or other addons installed (https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles).

**Comment by sneakypete81** [comment]
Closing, please indicate if you can provide steps to reproduce your problem.
