### ISSUE TITLE
Site stopped showing that it's updated.

### ISSUE THREAD

**Issue by molitar** [sneakypete81/updatescanner#288]
Thanks for creating a new issue!

Before continuing, please use the search box in the header above to check if someone has already reported it.

To help explain the issue, please include the following:
 * OS version: Windows 7 64-bit
 * Firefox version: 63.0b8
 * Update Scanner version: 4.3.0

#### Steps to reproduce the problem:
http://sakuracircle.animeholics.org/  (this is adult site but only covers are shown so safe on home page)

#### What you expected to happen:
The scanner will no longer show it being scanned the text is grayed out.  When I click it shows the page but it will not show that it's already been read and just remains grayed out.  This just started happening 2 days ago so not sure why it won't update anymore.

#### What actually happened:
![screenshot_2](https://user-images.githubusercontent.com/16074561/47054484-0e419c00-d180-11e8-919b-3a2c9ec25b6d.png)

**Comment by sneakypete81** [comment]
It's working for me, please try again.

If it's still not working, please try to reproduce your problem in a fresh profile with no configuration changes or other addons installed (https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles).

**Comment by molitar** [comment]
> 
> 
> It's working for me, please try again.
> 
> If it's still not working, please try to reproduce your problem in a fresh profile with no configuration changes or other addons installed (https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles).

Yeah working now. It was using Cloudflare it seems and must been timing out. Can we get a time out setting or that?  Cloudflare as you know typically gets activated when site starts to get attacked. It seems the time it takes for Cloudflare to check browser it times out and does not update.

**Comment by sneakypete81** [comment]
The fetch operation uses the standard Firefox timeout, as far asI can see. If the server doesn't respond within that time then having it appear greyed out seems like the right thing to do.

**Comment by molitar** [comment]
That is strange because I could still open it in Firefox just fine.  Maybe that is a bug because it sure was showing me the gray pretty quick and before it would have any chance to let Cloudflare detect browser.
