### ISSUE TITLE
Lost Sites

### ISSUE THREAD

**Issue by SteveP-UK** [sneakypete81/updatescanner#289]
* OS version: Wins 10 1809
 * Firefox version: 62.03
 * Update Scanner version: 4

#### Steps to reproduce the problem:
This is weird. Today when I opened up FF there we no pages in my Update Scanner list. I can see all the pages if I open Bookmarks (there's a folder called 'Update Scanner Pages'). I can also add new pages and they show up in Update scanner,as expected but my original list just isn't showing. I don't fancy having to add them all back in by hand, so is there anything else i can try. I've tried removing the addin and adding it back in but it makes no difference.
Any help appreciated Pete!

Cheers

Steve

**Comment by sneakypete81** [comment]
Please reopen if you can reproduce the problem.
You can backup and restore your pages from the menu in the toolbar popup panel:

![image](https://user-images.githubusercontent.com/38854/47256485-3d565700-d479-11e8-9765-45805393350e.png)

Also, note that v4.x no longer uses bookmarks to store its page list.

**Comment by SteveP-UK** [comment]
Cheers!

Job done. Happy bunny this end. Out of interest, now that v4 no longer uses
the bookmark principle, where is the data held? Is it under the Firefox
profile folder somewhere?

Regards

Steve

**Comment by sneakypete81** [comment]
Yes, it will be in one of the Firefox internal database files in the profile directory.

**Comment by gdillon6** [comment]
I also searched and can not find the database??

**Comment by sneakypete81** [comment]
I believe it's something like `storage/permanent/moz-extension+++5d5823d4-43a8-f74a-b2a3-78e418580c53`. It might vary depending on platform (and possibly even Firefox version).

**Comment by SteveP-UK** [comment]
Thanks. I'll take a look! ☺
