### ISSUE TITLE
Can't copy/paste from the debug page

### ISSUE THREAD

**Issue by johnhawkinson** [sneakypete81/updatescanner#291]
* OS version: OS X 10.12.6 (16G1510)
 * Firefox version: 62.0.3
 * Update Scanner version: 4.3.1

#### Steps to reproduce the problem:
I wasn't seeing a clear indication of the highlighting I'd expect, presumably because there was no rendering change, but I wanted to check. I'd recently discovered the Gear > "Debug Info" page, which I had previously missed. Having gone there, I was quite surprised I could not copy/paste the HTML out of the boxes, because I could not select text. (I realize I can download the files).

#### What you expected to happen:
Ability to select text.

#### What actually happened:
Can't select. Seems to be becuase of ` -moz-user-select: none;`.

Why is this CSS present and can it please be removed? I know better than the Extension whether I want to select something!

**Comment by sneakypete81** [comment]
Thanks, that's certainly not deliberate. Let me see why this is being applied.
