### ISSUE TITLE
Bookmark file .js update issue

### ISSUE THREAD

**Issue by ramesh17c** [sneakypete81/updatescanner#296]
Thanks for creating a new issue!

Before continuing, please use the search box in the header above to check if someone has already reported it.

To help explain the issue, please include the following:
 * OS version:
 * Firefox version:
 * Update Scanner version:

#### Steps to reproduce the problem:
[Include webpage URL, if applicable]

#### What actually happened:
[Include a screenshot]

**Comment by ramesh17c** [comment]
Firefox 63.0.1 (64-bit) ; Update Scanner 4.3.1

**Comment by sneakypete81** [comment]
Please see #171
