### ISSUE TITLE
Show updates UX is inconsistent about new tabs

### ISSUE THREAD

**Issue by johnhawkinson** [sneakypete81/updatescanner#297]
* OS version: OS X 10.12.6
 * Firefox version: 63.0.0
 * Update Scanner version: 4.3.1

The Update Scanner toolbar menu seems to offer an inconsistent user experience in choosing whether to open updates in new tabs. If, as usual, I select "Show All Updates," all updates are opened in new tabs, which is expected.

But if, rather less often (usually only if there are a lot of updates pending and I only want to check one), clicking on a single update causes that update to open in my current tab, replacing the currently open webpage.

The latter behavior is...unexpected. I don't know that it's wrong, but it certainly confused me for quite a while (weeks) before I realized what was going in ("Where did that tab I was reading a few minutes ago go?") until I finally figured it out and then it surprised me.

It seems like either the UI should be adjusted so there is a hint that the current page will be replaced, or maybe the behavior should change and clicking any item should open it in a new tab

My tendency is to think the UI should change, however I'm not sure what that ought to look like. Brainstorms, anyone?

Thanks.

**Comment by johnhawkinson** [comment]
I'm sorry, I didn't see this has substantial overlap with #286.
(I did run through all the open issues first, but obviously I didn't do a very good job.)
Although I guess that #286 doesn't talk about UI affordances and hints and such.

**Comment by sneakypete81** [comment]
> maybe the behavior should change and clicking any item should open it in a new tab

I'm leaning towards this option, although it would be a departure from the behaviour of the native Firefox popups (as mentioned in #286). I think it's probably safer and less confusing to open a new tab... but I would welcome other opinions.

**Comment by sneakypete81** [comment]
Thanks for your thoughtful comments, by the way.

**Comment by sneakypete81** [comment]
Closing in favour of #286 - thanks for your input.
