### ISSUE TITLE
Get message Javascript non-enabled

### ISSUE THREAD

**Issue by ThomasJack99** [sneakypete81/updatescanner#300]
On one page I get the message:
"Sorry, your browser does not support JavaScript or has it disabled, this site requires JavaScript."
The same question a couple of years ago got answered:
"Unfortunately Update Scanner only scans HTML, so can't be used for websites that require JavaScript to see the content. "
I just wondered if there is a work around?

**Comment by sneakypete81** [comment]
As you mentioned, Update Scanner can't run JavaScript, it just loads HTML from the website.

Some websites have mobile versions that serve HTML directly - you can try replacing the "www." with "m.".

**Comment by sneakypete81** [comment]
Duplicate of #83
