### ISSUE TITLE
Empty pages?

### ISSUE THREAD

**Issue by yolinfl** [sneakypete81/updatescanner#302]
Thanks for creating a new issue!

Before continuing, please use the search box in the header above to check if someone has already reported it.

To help explain the issue, please include the following:
 * OS version:
 * Firefox version:
 * Update Scanner version:

#### Steps to reproduce the problem:
[Include webpage URL, if applicable]

#### What actually happened:
[Include a screenshot]

**Comment by yermulnik** [comment]
Not sure is relevant, but for me UpdateScenner shows empty scan results pages on a FB container tab in my FF. Simply copy&paste'ing UpdateScanner URL to regular tab does the thing.
