### ISSUE TITLE
Failure to restore list from backup.

### ISSUE THREAD

**Issue by elmerehbi** [sneakypete81/updatescanner#307]
Ever since the Firefox changes and I cannot use Update Scanner.
Here are some details:

 * OS version: Ubuntu 18.04
 * Firefox version: Cannot find the version. It is snap packaged.
 * Update Scanner version: 4.3.1

#### Steps to reproduce the problem:
* Backup bookmakrs
* Click `Restore Pages` and select backup file

#### What you expected to happen:
To have the list imported.

#### What actually happened:
Failed to restore message.
![screenshot from 2019-01-14 00-11-57](https://user-images.githubusercontent.com/3155152/51091883-292ca800-1791-11e9-9db1-99a9dd4f2ef8.png)

**Comment by sneakypete81** [comment]
Would you mind sending me the .JSON backup file so I can see what's going wrong? updatescanner at gmail dotcom.

**Comment by sneakypete81** [comment]
Closing, please update if you have any further information.
