### ISSUE TITLE
google URLs show blank page

### ISSUE THREAD

**Issue by BillDavison** [sneakypete81/updatescanner#32]
Using Update Scanner with Google search URLs results in Old Page, New Page and Changes all showing a blank page.  Problem began mid to late Sep.  Before that, I had many Google URLs that worked fine.

Environment: Win7, Firefox 32.0.3, Update Scanner 3.2.0
I was able to duplicate the problem on an Ubuntu 14.04 machine with a plain vanilla Firefox install.  Version numbers for Firefox and Update Scanner were the same as above.

Sample URL: 
https://www.google.com/search?q=testing&ie=utf-8&oe=utf-8&aq=t&rls=org.mozilla:en-US:official&client=firefox-a&channel=sb

Image of blank Changes page:
![2014-10-01 20_13_48-c__temp2_2014-10-01 20_11_28-testing - google search png - greenshot image edito](https://cloud.githubusercontent.com/assets/8966109/4486089/ef762138-49d9-11e4-9fb7-aaf1f6df6b29.png)

**Comment by einst3** [comment]
if view raw source is implemented this would help but i would like to see changes to html after js finishes. i dont know if this could be accomplished. it would be up to the browser engine if you could intercept the html after page is done loading.

**Comment by Lambdac0re** [comment]
Will try the workaround...
