### ISSUE TITLE
Lots of text highlited but no change actually happened

### ISSUE THREAD

**Issue by NicolasLeMonde** [sneakypete81/updatescanner#324]
Windows 7 - Firefox 65 - UpdateScanner 4.3 I guess (dowloaded yesterday)

#### Steps to reproduce the problem:
- Program a hourly scan of a webpage from the Wirecutter site 
  (with any number of character) such as :
  https://thewirecutter.com/reviews/best-lightning-cable/
- Shut down your computer
- Relog the next morning

#### What you expected to happen:
- in the sidebar, see see the URL in a normal police if the text of the page has not changed 

#### What actually happened:
- in the sidebar, see the URL in bold
- click on it and see a lot of highlighted text, which is very unexpected
- compare the old and new versions and see that the text is exactly the same.

![old page](https://user-images.githubusercontent.com/47444677/52467012-53049f00-2b84-11e9-8b3e-9a0e8cf773e1.PNG)
![new page](https://user-images.githubusercontent.com/47444677/52467013-53049f00-2b84-11e9-9ac8-09eb70e0db74.PNG)
![highlighted](https://user-images.githubusercontent.com/47444677/52467014-539d3580-2b84-11e9-828f-9f9eb85fe8ea.PNG)

**Comment by sneakypete81** [comment]
I can't reproduce this, I've been trying for the past few days.

If it still happens for you, please try:
* Click the item in the sidebar
* On the far right of the banner, click the "Debug Info"
<img width="177" alt="image" src="https://user-images.githubusercontent.com/38854/52670474-86db1e00-2f10-11e9-856f-6bc0c825e387.png">
* Click the "Download" button for both the old and new HTML and compare them (you can use a tool like http://winmerge.org/ to help).

This will show the HTML changes that were detected.

**Comment by NicolasLeMonde** [comment]
Thanks Sneakypete
Didn't occur again here neither ...
I may have an explanation : the website that I monitor may have made a
modification on the structure of its page ?
I will let you know if it occurs again
Thanks :)

Le mar. 12 févr. 2019 à 22:56, sneakypete81 <notifications@github.com> a
écrit :

**Comment by sneakypete81** [comment]
That makes sense. Please reopen if it happens again and you can capture the changes in "Debug Info".
