### ISSUE TITLE
Show Status in Sidebar?

### ISSUE THREAD

**Issue by kstev99** [sneakypete81/updatescanner#327]
I'm not even sure this is possible with the Web Extension version, but I am thinking that the old version highlighted the link that was being checked in the sidebar as well as a little spinner showing that a check was in progress.  This would be a nice addition if it is at all possible.

**Comment by sneakypete81** [comment]
Would need to work out the UX, but bringing back this functionality would be useful.

**Comment by sneakypete81** [comment]
Actually, I think this is the same as #124
