### ISSUE TITLE
Folder managment suggestions

### ISSUE THREAD

**Issue by Ibgbg** [sneakypete81/updatescanner#332]
Hello!

I have been using Update Scanner for many years and I really appreciate all the hard work that is put in to it. A couple of months ago I started to use the new version, and even though I preferred the old version better, this one does the job to.

I do have two suggestions for how folder management could be improved:

1. In the old version of Update Scanner it was possible to have the content in folders sorted alphabetically, that was very useful when you have a large number of sites saved in one folder. It would be great if that came back.

2. One feature I often wished that that the old Updated Scanner had, but didn't, was the ability to change the settings for all the sites saved in a folder at once, for example from: “Manual scan only” to ”Scan every 6 hours”, without having to change the settings for each site, one by one.

I don't know if it's possible to add these two features but if it is, it would be a great improvement to an already very useful application.

**Comment by sneakypete81** [comment]
Thanks very much for your comments, I appreciate it. I think these are being tracked in #143 and #212, and I agree that these would be useful areas to improve.
