### ISSUE TITLE
Can Scan All Pages speed be increased?

### ISSUE THREAD

**Issue by Gitoffthelawn** [sneakypete81/updatescanner#333]
Thank you for the excellent extension.  Your hard work is appreciated! :+1: 

I'm trying out Update Scanner for the first time.  I want to use it a little differently than some people.  I want it to *only* scan on demand.  To accomplish this, I set each site to never check for updates, and then use the toolbar button, click on Menu, then Scan All Pages when I want to scan.

Overall, this seems to work quite well.  I did notice a possible bug that if you interact with Update Scanner while it is performing a "Scan All Pages" operation, it gets a bit wonky.  I wasn't able to easily reproduce, so I didn't file a bug report.

Anyways, back to this issue.  Is there any way to speed up the "Scan All Pages" operation?  I noticed that Update Scanner takes much longer to scan all the pages than Firefox does to load the pages.  And, from what I can tell (please correct me if I'm mistaken), Update Scanner only loads the main HTML of the site, whereas Firefox has to load all the external resources (which often 90% represents of the load).

**Comment by sneakypete81** [comment]
There's a 2-second delay between scanning pages. Often scanning is done in the background, so this is an attempt to prevent disruption to the user's browsing.

#1 should allow this delay to be set to zero.
