### ISSUE TITLE
SORT BY ALPHA.  Why is this impossible ??????? Its 2019

### ISSUE THREAD

**Issue by gdillon6** [sneakypete81/updatescanner#344]
Thanks for creating a new issue!

Before continuing, please use the search box in the header above to check if someone has already reported it.

To help explain the issue, please include the following:
 * OS version:
 * Firefox version:
 * Update Scanner version:

#### Steps to reproduce the problem:
[Include webpage URL, if applicable]

#### What actually happened:
[Include a screenshot]

**Comment by sneakypete81** [comment]
This is #143, I think.

**Comment by gdillon6** [comment]
Sorry if I sound stupid, but when it comes to this I am.  Still don't know
how to sort all these of mine??

**Comment by sneakypete81** [comment]
There is not currently a way of sorting automatically.

**Comment by gdillon6** [comment]
Okkkk thank you anyway!
