### ISSUE TITLE
Ignore changes to numbers not working on a page

### ISSUE THREAD

**Issue by Gitoffthelawn** [sneakypete81/updatescanner#346]
"Ignore changes to numbers" does not seem to be working on this page:
https://sourceforge.net/projects/naps2/files/

Why isn't it working there?  Can it be made to work?

**Comment by sneakypete81** [comment]
I would guess that there might be other changes to the page.

To see all changes to the raw HTML source, see the instructions at https://github.com/sneakypete81/updatescanner/wiki#how-do-i-see-why-a-page-was-identified-as-changed.

**Comment by Gitoffthelawn** [comment]
Message received.  I'll bookmark this and update next time I do a update scan.

**Comment by Gitoffthelawn** [comment]
Thanks for waiting patiently.  I performed an update, compared the raw HTML source, and here are the results:

The **visible** changes are only numbers.  They should all be ignored, per Update Scanner settings.

There are *many* non-visible changes to the page, including scripts and tracking numbers appended to links.  Does Update Scanner ignore these, or does it count them as changes?

**Comment by sneakypete81** [comment]
It ought to ignore them, although the scanner is sometimes mistakenly triggered by changes within tags. Please post the old and new html here, and I can take a closer look.

**Comment by Gitoffthelawn** [comment]
Thanks. Here they are, verbatim.  I renamed the html files to txt to make GitHub happy.

[NAPS2 - SourceForge-old.txt](https://github.com/sneakypete81/updatescanner/files/3141224/NAPS2.-.SourceForge-old.txt)
[NAPS2 - SourceForge-new.txt](https://github.com/sneakypete81/updatescanner/files/3141225/NAPS2.-.SourceForge-new.txt)

**Comment by Gitoffthelawn** [comment]
Here is the rest of the debug data:

>  https://sourceforge.net/projects/naps2/files/
scanRateMinutes:  0
changeThreshold:  10
ignoreNumbers:    true
encoding:         utf-8
highlightChanges: true
highlightColour:  #ffff66
markChanges:      false
doPost:           false
postParams:       null
state:            no_change

Curiously, `state`=`no_change`, but Update Scanner lists the page as one on which changes have taken place.  What is the meaning of `state`?

**Comment by sneakypete81** [comment]
There are various differences that will be detected as changes. For example, the "<title>2 weekly downloads</title>" on line 2557 of the old page isn't present in the new page.

The scanner doesn't recognise that this text is part of an embedded SVG. Unfortunately it wouldn't really be practical to extend this to cover all the possible non-visible changes that occur outside HTML tags.

**Comment by sneakypete81** [comment]
Closing, as the page was changing. Unfortunate there are some websites that just don't work very well with Update Scanner.
