### ISSUE TITLE
How can i export/import settings? 

### ISSUE THREAD

**Issue by alexforsikov** [sneakypete81/updatescanner#35]
Hi there! I promise, i wiil donate this great plugin, when i'll get answers to my questions :)
I have  Firefox 33.0, latest version of Update Scanner on MacOs 10.9.5 and 54 sites on scanning list. 
How can i export this list so i can scan for updates on other computer?

**Comment by jamiebbates** [comment]
Do the copies of each page transfer over as well? So, if I wanted to store like 4500 bookmarks, could I store them into different folders on my personal network and import/export them into the scanner when I want to update them? (probably about 50-100 bookmarks per folder). Will the imprint of the page be saved as well as the bookmark settings?

**Comment by sneakypete81** [comment]
No, the page copies themselves are stored in your local Firefox profile, not inside the bookmark system.

**Comment by drumsibumsi** [comment]
The biggest pain is that the settings per each page are also not transferred with the bookmarks. Hope some day the import/export functions would appear in the plugin! Thanks anyway!

**Comment by sneakypete81** [comment]
They should be - make sure you're backing up in JSON format, not HTML. See https://support.mozilla.org/kb/restore-bookmarks-from-backup-or-move-them for details.
