### ISSUE TITLE
Failed to restore pages

### ISSUE THREAD

**Issue by soyelfede** [sneakypete81/updatescanner#354]
Hello, I apologize but again I have a problem to restore the pages.
I reinstalled OS Mojave from scratch on my MacBook Pro (Mid 2012). I want to restore the UpdateScanner pages that I saved in the file redirection-www-recursoscultural-com-25-febrero-2019.json but when I import it from UScanner / Menu / Restore Pages it opens an error page with the message Failed to restore pages.Thanks for creating a new issue!

Regards

 * OS version: Mojave
 * Firefox version: 65.0.1
 * Update Scanner version: 4.3.2

![Captura de pantalla 2019-03-15 a la(s) 15 14 52](https://user-images.githubusercontent.com/47217687/54452992-2587b400-4735-11e9-8d88-1966702315e6.png)

**Comment by sneakypete81** [comment]
If you are happy to send me the .json file, I can check why it's not importing into Update Scanner. You can email it to "updatescanner (at) gmail (dot) com".

**Comment by sneakypete81** [comment]
Resolved by email
