### ISSUE TITLE
Respect anchors in URLs

### ISSUE THREAD

**Issue by Gitoffthelawn** [sneakypete81/updatescanner#364]
When a URL with an anchor is added to Update Scanner, and a change in the page is found, Update Scanner does not scroll to the anchor when it displays the page.

For example: https://www.cpuid.com/softwares/hwmonitor.html#version-history

**Comment by sneakypete81** [comment]
I'm not sure that this is possible. The stored HTML is injected into a sandboxed iframe with all scripting disabled. I can't think of a way of adding the ability to scroll to an anchor, unfortunately.

**Comment by Gitoffthelawn** [comment]
Thanks.  When it's injected, is the anchor included?  I thought the browser handled the scrolling natively, but perhaps it doesn't work in an iframe.
