### ISSUE TITLE
No file open prompt for restore pages

### ISSUE THREAD

**Issue by n00mad** [sneakypete81/updatescanner#371]
Hello,
I don't get a file open prompt after selecting restore pages on a Linux box.  Restore pages does work on my Mac with Firefox Dev Edition.
Firefox: 66.0.2
Linux: Ubuntu18.04 and also Ubuntu16
"Backup Pages" does work on both Ubuntu versions.

When I requested restore via the web gui drop down menu it opened a tab with the following in the tab uri:
moz-extension://6b73ede1-c6d3-479e-8c1c-26878b2cad39/app/restore/restore.html

The new tab and web gui restore page drop down never go away.  And there is never a prompt for which file to use to restore.

Is there a file(s) I can copy from my old firefox profile to my new firefox profile that will allow me to use updatescanner while this problem is researched and fixed?

Thanks,
n00mad

**Comment by mlep** [comment]
I had a similar issues. If I recall correctly, it came from addons that block pop-up windows. Please, try to restart firefox without add-ons, Update Scanner excepted.

**Comment by sneakypete81** [comment]
Thanks, I can reproduce this on Linux too. I've made a fix, I'll try to get this into a beta release soon.

**Comment by sneakypete81** [comment]
Unfortunately there's no way to work around this easily without using the restore function.

**Comment by sneakypete81** [comment]
Please try the latest beta release - install instructions are at #36.

**Comment by n00mad** [comment]
Loaded the xpi per instructions.  Cannot attach a tiff to show confirmation.  I'll work on that.
Still same results.

I am not sure if this is workaround or a fix; but based on a suggestion earlier in the thread, I found that I had popups blocked in preferences.
I added an exception of: moz-extension://6b73ede1-c6d3-479e-8c1c-26878b2cad39/app/restore/restore.html

And restore pages worked.  

still willing to try out other solutions if that is a workaround and not a fix.

**Comment by n00mad** [comment]
attachment, I hope.

**Comment by mlep** [comment]
Oh, yes, you are right: it was not about addons, it was about blocked pop-pups as defined in the preferences. Sorry, I had this issue several months ago...

**Comment by sneakypete81** [comment]
The latest beta (4.4.0beta2) should now work with popup blocking enabled. Thanks for reporting this.

**Comment by n00mad** [comment]
Confirmed 440 beta2  works for restore pages with popup blocking enabled.
I made a json backup.
i removed all block popup exceptions.  i loaded 440 beta2.
i restarted the browser as a pre-caution.
i restored from the json backup using select button offered after the restore qui selection.
Thanks!!
