### ISSUE TITLE
Google captcha issue?

### ISSUE THREAD

**Issue by mrsilva** [sneakypete81/updatescanner#38]
I believe that UpdateScanner will cause Google captchas (when you're searcching Google and Google asks you to prove you're human by entering the text in the Captcha).

I have over 200 URLs that I scan at several frequencies. If I disable UpdateScanner in Firefox I stop getting Google captchas after a couple of days. If I enable it I start getting Google captchas randomly once or twice per day.

I'm not sure what could be causing this. Could it be the fact that I'm using Google DNS servers? Does UpdateScanner ask for name resolution for all URLs at the same time?

Has anybody else experienced this?

**Comment by sneakypete81** [comment]
Please reopen if you have any further information
