### ISSUE TITLE
Delete GUI bug with Updatescanner 4.4.0b2

### ISSUE THREAD

**Issue by molitar** [sneakypete81/updatescanner#381]
Thanks for creating a new issue!

Before continuing, please use the search box in the header above to check if someone has already reported it.

To help explain the issue, please include the following:
 * OS version: Windows 10 64 bit
 * Firefox version: Firefox DE 65.02b
 * Update Scanner version: 4.4.0 beta 2

#### Steps to reproduce the problem:
Try to delete any in the sidebar and the words delete are hidden among the list and the actual button to say yes or no is also hidden in the sidebar and is basically just text.

#### What you expected to happen:
To see a small dialogue box asking to confirm if I want to delete or not.. Not hidden among the text and taking the entire sidebar up for the text is hidden somewhere in the middle of the sidebar and the confirmation buttons is hid near the bottom of the sidebar.

#### What actually happened:
![screenshot](https://user-images.githubusercontent.com/16074561/56067463-37b33d00-5d49-11e9-9570-6d78cf0cc869.png)

**Comment by sneakypete81** [comment]
Confirmed, a recent Firefox update has broken this.

**Comment by sneakypete81** [comment]
Please try 4.4.0beta3 - see #36 for instructions.

**Comment by molitar** [comment]
4.4.0beta3 did fix this bug.
