### ISSUE TITLE
Request old feature back: Mark all read

### ISSUE THREAD

**Issue by molitar** [sneakypete81/updatescanner#382]
This was actually an old feature in the old version.  Sometimes some pages just do not want to identify as being read so at them times I could use option mark all read and clear the status.  This feature was also nice if you were offline for a while like a vacation or that it was much easier to mark all read and let it start monitoring again.

**Comment by SteveP-UK** [comment]
+1 to this!

**Comment by sneakypete81** [comment]
See #185.
