### ISSUE TITLE
Restore - can't open file 

### ISSUE THREAD

**Issue by grabbyx** [sneakypete81/updatescanner#384]
* OS version: Windows 10
 * Firefox version: 66.0.3 (64-Bit)
 * Update Scanner version: 4.3.2.

I have a backup of UpdateScanner Pages.
I want to restore the file.
If I press restore a new empty tab opens showing
moz-extension://0996f441-fa79-4e4a-9c7e-5153384e3db6/app/restore/restore.html
But I can't chose a file.

**Comment by sneakypete81** [comment]
See #371
