### ISSUE TITLE
Plugin disabled due Firefox recent sign verify issue

### ISSUE THREAD

**Issue by khaninejad** [sneakypete81/updatescanner#396]
Thanks for creating a new issue!

Before continuing, please use the search box in the header above to check if someone has already reported it.

To help explain the issue, please include the following:
 * OS version: win 10
 * Firefox version: 66.0.3
 * Update Scanner version: 4.4.0

Today my whole plugins disabled include updatescanner with this message:
"Update Scanner could not be verified for use and has been disabled."

**Comment by sneakypete81** [comment]
This is a Firefox issue, https://bugzilla.mozilla.org/show_bug.cgi?id=1548973

**Comment by sneakypete81** [comment]
Public announcements here: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047

**Comment by yermulnik** [comment]
Wow, people made that site go down at the moment:
```
503 Service Unavailable
No server is available to handle this request. 
```
