### ISSUE TITLE
updatescanner could not have been verified for use in Firefox and was forbidden

### ISSUE THREAD

**Issue by MaMiMr** [sneakypete81/updatescanner#397]
* OS version: Windows 10 Version 1809 
 * Firefox version: 66.0.3 (64 bite)
 * Update Scanner version: 4.4.0

But I noticed you mentioned https://bugzilla.mozilla.org/show_bug.cgi?id=1548973 as Firefox developers are aware of the situation with AddOns and are working the problem. 

Thanks.

**Comment by sneakypete81** [comment]
Yes, see #396
