### ISSUE TITLE
New rule: if more then XX % of the page change ignore and wait again YYmin

### ISSUE THREAD

**Issue by Mannshoch** [sneakypete81/updatescanner#418]
* OS version: Windows 10
 * Firefox version: 66.0.5
 * Update Scanner version: 4.4.0

#### Steps to reproduce the problem:
Choose a Website with session based login.
After restart Firefox the updatescanner check only shows me a login page as a big change.

#### What you expected to happen:
I could setup that Update scanner ignores changes that are grater then e.g. 80% and wait then an additional amount of time and recheck again.
(It's may need also an option to show the percentage of the current change of a site to bee able to set normal changes in context and develop a maximal percentage value for the settings.)

#### What actually happened:
updatescanner check a login Page.

**Comment by sneakypete81** [comment]
Thanks for the suggestion. Unfortunately I don't think this is something that we'll be able to easily implement
