### ISSUE TITLE
Where can I find older XPI file for installing into older versions of firefox

### ISSUE THREAD

**Issue by tweiner** [sneakypete81/updatescanner#420]
I am sorry this is not exactly an issue.  I am just trying to downgrade firefox for some other extensions and want to reinstall Update Scanner.

Also is there a way to import an older scan list that is saved in the firefox extension file.

Actually is there a way to export/ import a list of URLs to scan?

Thanks

Tweiner

**Comment by sneakypete81** [comment]
All past versions are available from the Firefox Add-ons website: https://addons.mozilla.org/en-GB/android/addon/update-scanner/versions/

You can backup and restore by clicking the toolbar button and then the "menu" button (with three dots) at the bottom of the popup.
