### ISSUE TITLE
Sometimes ignoring address line

### ISSUE THREAD

**Issue by radpopl** [sneakypete81/updatescanner#45]
Steps:

1. Open http://otomoto.pl
2. Click "Samochody osobowe", click "Acura" (http://otomoto.pl/osobowe/acura)
3. Enter "10000" at field "Cena: / od".
4. Address line should change to "http://otomoto.pl/osobowe/acura?fq%5Bprice%5D%5Bfrom%5D=20000"
5. Try to add this page to Update Scanner (Scan page) -- Update Scanner proposes previous link "http://otomoto.pl/osobowe/acura" (should "http://otomoto.pl/osobowe/acura?fq%5Bprice%5D%5Bfrom%5D=20000")

**Comment by sneakypete81** [comment]
This particular website changes the URL bar dynamically without reloading the page. Update Scanner doesn't notice that the address has changed.

I'll look at ways of detecting this properly - thanks for reporting. For now you can just copy/paste the URL from the address bar manually.

**Comment by sneakypete81** [comment]
The page's URL is currently obtained as follows:

    var mainWindow = window.QueryInterface(Components.interfaces.nsIInterfaceRequestor)
                   .getInterface(Components.interfaces.nsIWebNavigation)
                   .QueryInterface(Components.interfaces.nsIDocShellTreeItem)
                   .rootTreeItem
                   .QueryInterface(Components.interfaces.nsIInterfaceRequestor)
                   .getInterface(Components.interfaces.nsIDOMWindow);

    var url = mainWindow.content.document.URL;
    var title = mainWindow.content.document.title || url;

There are a number of alternative ways to get the URL of the current page - we should experiment to see which works best.

**Comment by sneakypete81** [comment]
@radpopl: this is working for me now. Can you please confirm whether you're still seeing this problem?

**Comment by radpopl** [comment]
For me now is working OK. Thanks!

**Comment by sneakypete81** [comment]
Great, thanks for checking.
Seems like a Firefox bug that has since been fixed.
