### ISSUE TITLE
Update Scanner is not working in 67.0.1 (64-bit)

### ISSUE THREAD

**Issue by FloridaGreg** [sneakypete81/updatescanner#453]
Thanks for creating a new issue!

Before continuing, please use the search box in the header above to check if someone has already reported it.

To help explain the issue, please include the following:
 * OS version:
 * Firefox version:
 * Update Scanner version:

#### Steps to reproduce the problem:
[Include webpage URL, if applicable]

#### What actually happened:
[Include a screenshot]

**Comment by Isometer2** [comment]
OS version: Windows 10 64 bit
Firefox version: 67.0.1
Update Scanner version: 4.4.0
Steps to reproduce the problem:
For the following pages a change is displayed and only one blank page is opened:
https://www.vde-verlag.de/normen/neuerscheinungen/?fassung=alle&bereich=alle&sortiert-nach=ausgabedatum&richtung=absteigend
https://www.vde-verlag.de/iec-normen/neuerscheinungen/
What you expected to happen: Display of website changes
What actually happened: The app only opens a blank page

**Comment by btanner2** [comment]
Confirmed!

**Comment by molitar** [comment]
Use the Developer edition for Firefox like I am it works perfectly.

**Comment by Travellingman** [comment]
Or just update to 67.0.3 where it works.

**Comment by Isometer2** [comment]
In the developer version, as well as in versions up to 67.0.4 (64-bit), the above pages do not work.

**Comment by btanner2** [comment]
Firefox version: 68.0.
Update Scanner stopped working again today. All pages opens only a blank page. The only way to get it back to work is to 
-	export all pages to a file
-	delete plugin 
-	reinstall the plugin
-	import the pages from backup
It works for a while and stopped working after some time. I am using Update Scanner for years, this is the first time, something like this happens.

**Comment by btanner2** [comment]
Unfortunately I have to correct myself. I didn’t get Update Scanner back to work. I tried:
-	Uninstalling the add-on
-	Restarting Firefox
-	Reinstalling  the add-on
-	New pages like https://example.com/ stay blank forever, such as the restored pages from the add-on
-	Nothing works
The only way to fix is, seems to create a completely new Firefox profile, after this, the add-on works without any issues. The question is, what can I do here? I do not want to use a new FF profile. All other add-ons work without any issues in the current profile …

@ sneakypete81: could you help me?

**Comment by sneakypete81** [comment]
@btanner2: it's good that you have it working in a new profile. I'd suggest comparing the Firefox preferences between the two profiles, particularly the security and privacy sections, to see if there are any differences.

**Comment by molitar** [comment]
> 
> 
> Unfortunately I have to correct myself. I didn’t get Update Scanner back to work. I tried:
> 
>     * Uninstalling the add-on
> 
>     * Restarting Firefox
> 
>     * Reinstalling  the add-on
> 
>     * New pages like https://example.com/ stay blank forever, such as the restored pages from the add-on
> 
>     * Nothing works
>       The only way to fix is, seems to create a completely new Firefox profile, after this, the add-on works without any issues. The question is, what can I do here? I do not want to use a new FF profile. All other add-ons work without any issues in the current profile …
> 
> 
> @sneakypete81: could you help me?

When this happened to me I installed older stable release and it worked then I reinstalled the beta and it still worked.

**Comment by btanner2** [comment]
Hi again,

I just found out, what makes Update Scanner to show only blank pages, instead of the highlighted changes. It is the setting **firstPartyIsolation**. You can change this setting easily by using this add-on:

https://addons.mozilla.org/de/firefox/addon/first-party-isolation/

If firstPartyIsolation is enabled: Update Scanner shows only blank pages
If firstPartyIsolation is disabled: Update Scanner works normally

@sneakypete81: Could you please investigate here to check if this is fixable?

Thanks a lot
Brian

**Comment by sneakypete81** [comment]
@Isometer2, could you please try to see if this happens with a new profile? See https://github.com/sneakypete81/updatescanner/wiki#what-should-i-do-if-i-find-a-bug.

@btanner2: unfortunately this setting seems to break Update Scanner, and I don't think there's an easy workaround.

**Comment by sneakypete81** [comment]
Closing for now, please update if you can provide further information after installing from a fresh profile.

**Comment by FloridaGreg** [comment]
How do I import the pages from my backup json file. Firefox made me create a new profile and now the Update Scanner tab is empty.My last backup is 2019. Is there something in my last full backup I can use to restore?HELP! From: Brian Tanner ***@***.*** Sent: Tuesday, July 16, 2019 12:38 AMTo: sneakypete81/updatescannerCc: FloridaGreg; AuthorSubject: Re: [sneakypete81/updatescanner] Update Scanner is not working in 67.0.1 (64-bit) (#453) Firefox version: 68.0.Update Scanner stopped working again today. All pages opens only a blank page. The only way to get it back to work is toexport all pages to a filedelete pluginreinstall the pluginimport the pages from backupIt works for a while and stopped working after some time. I am using Update Scanner for years, this is the first time, something like this happens.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Travellingman** [comment]
Open UpdateScanner with the up-arrow, click the menu selection, and restore pages from your backup. 

---------- Original Message ----------

**Comment by Travellingman** [comment]
After considerable digging, I have found that IF you have Firefox set to NEVER REMEMBER HISTORY in Settings, Privacy & Security, History, the data will not be stored.   

---------- Forwarded Message ----------
