### ISSUE TITLE
Facebook, Youtube, and Twitter don't seem to scan right.

### ISSUE THREAD

**Issue by elrod1** [sneakypete81/updatescanner#469]
(Not sure if that's the term I'm looking for or not.)

 * OS version: Win 10 Home, Version 1803 OS Build 17134.829
 * Firefox version:  67.0.4 (64-bit)
 * Update Scanner version:  4.4.0

#### Steps to reproduce the problem:  Disabled all add ons except updatescanner.  Also tried it with a fresh profile with only update scanner added.
[Include webpage URL, if applicable]

#### What actually happened:  (turned on Fireshot to take these screenshots)
[#12097 - moz-extension___9542e16c-c36d-4ede-ae0f-449df1163c64_app_main_main_html_action=show_diff&id=220 - 06 27 2019 - 1920.pdf](https://github.com/sneakypete81/updatescanner/files/3337327/12097.-.moz-extension___9542e16c-c36d-4ede-ae0f-449df1163c64_app_main_main_html_action.show_diff.id.220.-.06.27.2019.-.1920.pdf)
[#12096 - moz-extension___9542e16c-c36d-4ede-ae0f-449df1163c64_app_main_main_html_action=show_diff&id=221 - 06 27 2019 - 1920.pdf](https://github.com/sneakypete81/updatescanner/files/3337328/12096.-.moz-extension___9542e16c-c36d-4ede-ae0f-449df1163c64_app_main_main_html_action.show_diff.id.221.-.06.27.2019.-.1920.pdf)
[#12098 - moz-extension___9542e16c-c36d-4ede-ae0f-449df1163c64_app_main_main_html_action=show_diff&id=222 - 06 27 2019 - 1921.pdf](https://github.com/sneakypete81/updatescanner/files/3337329/12098.-.moz-extension___9542e16c-c36d-4ede-ae0f-449df1163c64_app_main_main_html_action.show_diff.id.222.-.06.27.2019.-.1921.pdf)
[Include a screenshot]

Please let me know if you need more information. 

Thanks.

**Comment by sneakypete81** [comment]
Unfortunately Update Scanner can only detect changes in HTML content. Sites that use JavaScript to display content are unlikely to work well with Update Scanner.

Sometimes sites offer an HTML-only mode, but I've not tried this with FB/YT/Twitter.

**Comment by sneakypete81** [comment]
#83

**Comment by sneakypete81** [comment]
Please see also https://github.com/sneakypete81/updatescanner/wiki#why-do-some-websites-not-work.
