### ISSUE TITLE
Synchronising between multiple devices

### ISSUE THREAD

**Issue by katejgib** [sneakypete81/updatescanner#47]
After synchronsing my list of sites to scan, when looking at Update Scanner on two different PCs, my list no longer shows the unread pages (all pages appear as read). Is there a way to sync the sites and still be able to see changed sites (ie, those in bold)?

**Comment by sneakypete81** [comment]
Update Scanner isn't designed to work across multiple machines. Although you can probably keep the page list in sync by synchronising your bookmarks, it also stores local copies of each web page and uses these to detect changes to the live website. Unfortunately I don't think there's a way of reliably synchronising these local copies between multiple computers. 

> my list no longer shows the unread pages (all pages appear as read)

Are subsequent changes detected as normal and shown in bold?
