### ISSUE TITLE
Feature request: choose highlighter color

### ISSUE THREAD

**Issue by ragues** [sneakypete81/updatescanner#48]
I'm currently monitoring a site that uses yellow text on a black background. The shade is so close to updatescanner highlighter that the text is unreadable. So it would be good to be able to choose the highlight colour in updatescanner on a per-page basis.

**Comment by sneakypete81** [comment]
You can do this already:
* Right-click on a site in the sidebar and select "Properties"
* Click "Advanced" in the page properties dialog

![colour picker](https://cloud.githubusercontent.com/assets/38854/6737075/320db3d8-ce61-11e4-980d-976f6e762718.png)
