### ISSUE TITLE
Update Scanner completely broken

### ISSUE THREAD

**Issue by Alice-Cheshire** [sneakypete81/updatescanner#513]
Thanks for creating a new issue!

Before continuing, please use the search box in the header above to check if someone has already reported it.

To help explain the issue, please include the following:
 * OS version: 64-bit Windows 10 (1709)
 * Firefox version: 69.0
 * Update Scanner version: 4.4.0

#### Steps to reproduce the problem:
Unknown

#### What you expected to happen:
Update Scanner to actually work

#### What actually happened:
For some reason the last couple of days Update Scanner wasn't actually scanning pages even when I manually told it to. This culminated in today where I uninstalled and reinstalled the addon hoping that would work only for it to fail to even restore my backed up pages. When I try it just sits there on the "restoring pages, please wait" page forever, even when I use an older backup.

On top of that I'm having an issue with even adding new pages after the reinstall. It adds a new page but it fails to store any data on it at all. No url to watch, the title is just "New Page" no matter what I've entered, and the scan settings are "scan every day" and "ignore small changes" even when I've set them to something different.

I haven't installed any new addons recently that should be causing a conflict or anything so I have no idea what the problem could be here since the last update for the addon was a month ago. The only thing that seems to line up is the 69.0 update for Firefox.

**Comment by sneakypete81** [comment]
Please try with a fresh profile (see the instructions here: https://github.com/sneakypete81/updatescanner/wiki#what-should-i-do-if-i-find-a-bug). Hopefully that will help pinpoint where the problem is.

**Comment by Alice-Cheshire** [comment]
Oddly enough it seems to be working fine now. I decided to try importing my backed up settings one more time before doing what you suggested and this time it randomly decided to work.
