### ISSUE TITLE
Allow for custom entry of update interval

### ISSUE THREAD

**Issue by bigmittens** [sneakypete81/updatescanner#52]
I'm checking for updates on an API, and don't really care about the memory usage. I'd like to change the update interval to below 5 minutes.

**Comment by Keith94** [comment]
https://github.com/sneakypete81/updatescanner/issues/21#issuecomment-55081407

**Comment by sneakypete81** [comment]
To get an update interval below 5 minutes, you're much better off with a custom script (should hopefully be fairly easy if you're using an API!)
