### ISSUE TITLE
Can't find changes on https://www.cerberusapp.com/downloads

### ISSUE THREAD

**Issue by eXPerience83** [sneakypete81/updatescanner#522]
Thanks for creating a new issue!

Before continuing, please use the search box in the header above to check if someone has already reported it.

To help explain the issue, please include the following:
 * OS version: Windows 10
 * Firefox version: 69.0.1
 * Update Scanner version: 4.4.0

#### Steps to reproduce the problem:
[Include webpage URL, if applicable]
https://www.cerberusapp.com/downloads

#### What you expected to happen:
Find any changes, try to see at least "new page" when scanned from plugin

#### What actually happened:
[Include a screenshot]
Never shows any changes, always blank screen when try to scan from plugin

**Comment by sneakypete81** [comment]
This site doesn't display anything if Javascript is disabled. See https://github.com/sneakypete81/updatescanner/wiki/Home/_edit#why-do-some-websites-not-work for more details.
