### ISSUE TITLE
Update Scanner 4.5.0beta1 not updating page at all

### ISSUE THREAD

**Issue by molitar** [sneakypete81/updatescanner#524]
Thanks for creating a new issue!

Before continuing, please use the search box in the header above to check if someone has already reported it.

To help explain the issue, please include the following:
 * OS version: Windows 10 Pro build 1903
 * Firefox version: 69.0b7
 * Update Scanner version: 4.5.0b1 

#### Steps to reproduce the problem:
https://exhentai.org/?f_search=English+-futanari+-yaoi
 (warning adult site)

#### What you expected to happen:
plugin shows page has changed when I right click and scan. I click on the bold text and the page does not change. I than click on the frame header for Update Scanner that is titled 'Exhentai English' and page shows all the new updates.  This problem just started occurring today and not updating properly.

#### What actually happened:
I truncated the very top of the pictures so no adult content is show here.
![screenshot 1](https://user-images.githubusercontent.com/16074561/65838031-88edc380-e2cc-11e9-9041-d20bf1c78c7a.jpg)

![Screenshot 2](https://user-images.githubusercontent.com/16074561/65838032-8db27780-e2cc-11e9-8766-0fdf4ff1a17f.jpg)

As you can see from the pictures the new doujin are not appearing at all. Problem started today.

**Comment by sneakypete81** [comment]
Please show an example with a non-adult site

**Comment by molitar** [comment]
It may have been a Firefox problem.. I updated to the latest 69.0b14 and not seen the problem again. I originally tried 70 but UpdateScanner was completely broken in 70 so I than installed 69.0b07 and a simple edit of the ini file will fix the you updated from older version create a new profile.
 
All seems to be functional in 69.0b14 so far so I expect it was some sort of problem with the b07 release.
