### ISSUE TITLE
Add support for Pale Moon

### ISSUE THREAD

**Issue by KNTRO** [sneakypete81/updatescanner#53]
Hi Pete,

I can't remember if I already asked you for this somewhere in the past, but if so, here it goes again: **Please, add support for the Pale Moon 25.4 web browser‼** I really love this add-on but it's not compatible with this browser.

Please, consider do it so.

Thank you very much in advance!

**Comment by nelegalno** [comment]
I second that, here is some info that might help:
http://dev.addons.palemoon.org/jetpack/
https://www.palemoon.org/technical.shtml
https://addons.palemoon.org/resources/incompatible/

***P.S.*** I'd highly recommend reading [BLOG: This is rumor control, here are the facts.] (https://forum.palemoon.org/viewtopic.php?f=4&t=7818) before believing any rumors about PaleMoon and also consider the v25.4.1 as up to date since it is independent and not based on the version scheme used by FireFox.

**Comment by KNTRO** [comment]
@nelegalno Thank you nelegalno for helping with these "shortcuts", let's say! :)

**Comment by sneakypete81** [comment]
Hi both,

Unfortunately I don't have the bandwidth to support multiple browser platforms - it's enough work just keeping up with new Firefox versions.

But I would welcome any pull requests if anyone would like to add support for Pale Moon. It may just involve taking an older version of Update Scanner and adding the Pale Mood GUID to scripts/install.rdf.build.

Pete

**Comment by nelegalno** [comment]
v3.1.13 works fine, somewhere after that you added a clause that it requires higher version of FF whether it does or not is another question that I can't answer. Why not contact the team behind PaleMoon and see if they'll agree to help?

**Comment by sneakypete81** [comment]
I set the minimum FF version to the lowest version that the release has been tested with.

If you or someone else is willing to test more recent Update Scanner versions with Pale Moon, then it should be straightforward to add a GUID and supported version range for Pale Moon. There's a basic list of test steps in https://github.com/sneakypete81/updatescanner/blob/master/RELEASE_CHECKLIST.

But if 3.1.13 works for you already then I'd suggest just using that version.

**Comment by nelegalno** [comment]
I've just made a quick test with the development version and it seems to be working fine on PM v25.6

**Comment by KNTRO** [comment]
@nelegalno said:
> Why not contact the team behind PaleMoon and see if they'll agree to help?

The Pale Moon team often say that if the latest version of an add-on ain't compatible with Pale Moon, then one should try an older version instead. If an older version works OK, then there's no need to fix it, unless that older version of an add-on become an useless mess. :joy_cat: So, I guess I should keep using version 3.1.13.1-signed.

**Comment by nelegalno** [comment]
I'm happy to report that v3.2.3 works fine with PM v25.6 once it's GUID is added to install.rdf.

**Comment by nelegalno** [comment]
No problems with PaleMoon v25.7.0 and UpdateScanner v3.2.3 after adding the PM GUID.
