### ISSUE TITLE
Update Scanner 4.4.0 not working in Firefox 69.0.3 (64-bit)

### ISSUE THREAD

**Issue by travelrobb** [sneakypete81/updatescanner#537]
Thanks for creating a new issue!

Before continuing, please use the search box in the header above to check if someone has already reported it.

To help explain the issue, please include the following:
 * OS version: Mac 10.12.6
 * Firefox version: 69.0.3 (64-bit)
 * Update Scanner version: 4.4.0

I have many pages set to update on either 15-minute, 1-day, or one-week intervals. With all of the eBay pages, I get an error message: "This page returned an error when scanned. Click the above title to see what's wrong."
![Screen Shot 2019-10-11 at 4 44 46 PM](https://user-images.githubusercontent.com/17786604/66683877-94cf7300-ec46-11e9-96f8-4930ad3b0b94.png)
![image](https://user-images.githubusercontent.com/17786604/66683905-a7e24300-ec46-11e9-89ae-5cffbcee5a92.png)
When I click on the title/link to the page, the page opens normally.

In other instances, the pages report as being scanned, but the area where the page should be shown is blank.
![Screen Shot 2019-10-11 at 4 48 37 PM](https://user-images.githubusercontent.com/17786604/66684122-4e2e4880-ec47-11e9-9483-10cf3ef3b5b8.png)

Finally, I can't figure out how to delete expired pages from my update scanner library.

I'm not a developer, and know nothing about coding, so please be patient with me. 

Thanks!
-rm

**Comment by molitar** [comment]
Make sure fingerprint protection is not enabled in about:config.  The new version with that feature broke it for me.. disabled that protection and all is well again.

**Comment by sneakypete81** [comment]
Please try to see if this happens with a new Firefox profile - see https://github.com/sneakypete81/updatescanner/wiki#what-should-i-do-if-i-find-a-bug.

You can delete a page by right-clicking it in the Update Scanner sidebar.

**Comment by sneakypete81** [comment]
Closing for now, please update this if you have any further information.
