### ISSUE TITLE
Missing "Enable Javascript" and "Enable Flash" options

### ISSUE THREAD

**Issue by hmijail** [sneakypete81/updatescanner#57]
I am using Firefox 42b8 on OS X 10.11, and those options are not present in the options sheet. Only "Highlight changes" is there.

For what it's worth, I don't remember having seen those options on the last few Firefoxes in Linux either.

**Comment by sneakypete81** [comment]
See #31. Unfortunately this feature was lost when we switched to a more efficient way of loading pages.

**Comment by hmijail** [comment]
So then I would suggest removing the mentions / screenshots in https://addons.mozilla.org/en-GB/firefox/addon/update-scanner .

**Comment by sneakypete81** [comment]
Good point. They also need removing from https://sneakypete81.github.io/updatescanner/page_properties.html

**Comment by sneakypete81** [comment]
To answer your question: Javascript is not run at the moment. The scanner only detects changes to static HTML content anyway, so it's not really suited to dynamic websites.
