### ISSUE TITLE
No images loading with FF 41.0.2 / Slow

### ISSUE THREAD

**Issue by roooots** [sneakypete81/updatescanner#58]
Hi,

I do love Update Scanner and have been using it for more than a year or so. Now since a couple of weeks (unfortunately can' tell how long exactly), the scanner stopped showing images on http://www.ebay-kleinanzeigen.de with my FF41.0.2 on Ubuntu. Furthermore, when the notification pops up, I click on it and the extra 5..15 tabs appear on the tab bar, it will take between 10s and a couple of minutes before all tabs are filled with the respective content.

I've disabled any blocking addons but it did not make a difference.

Any suggestions on where to look for a solution?!

Thanks,
roooots

**Comment by sneakypete81** [comment]
That URL works fine for me, although I'm using FF42 on Ubuntu. It might be that you have another addon installed that is interfering with Update Scanner. Please try with a fresh profile and see if the problem is still present (see https://support.mozilla.org/en-US/kb/Managing%20profiles).

**Comment by roooots** [comment]
Thanks for the reply! Meanwhile, I'm on FF42 and just tried a fresh profile, with UpdateScan being the first and only plugin installed. Still - same issue here. Any suggestions how to debug?

Thanks,
r.

**Comment by sneakypete81** [comment]
That is puzzling, I can't think of any reason for this.

Is it just this URL that is causing this problem?

**Comment by roooots** [comment]
Just tried again and - no, it's not the only page. See the attached screeners, the URLs are:

http://www.ebay-kleinanzeigen.de/s-rolleiflex/k0
http://www.photographyreview.com/

Thanks for your support so far!
r.

![updatescanner_2](https://cloud.githubusercontent.com/assets/15329231/11132228/00ee8b6c-898f-11e5-896d-ac510bfa38bf.png)
![updatescanner_1](https://cloud.githubusercontent.com/assets/15329231/11132227/00ebe4d4-898f-11e5-9970-4acef64e98dd.png)

**Comment by sneakypete81** [comment]
Ah, both of those URLs use Javascript to load the images. If you disable Javascript and load the  pages normally (outside Update Scanner) then you'll see the same effect.

The original URL you posted doesn't contain Javascript, so the images should load correctly in Update Scanner.

There's no easy way of safely supporting Javascript when highlighting changes, but you can always click the "Current Page" view to see the page in all its Javascript glory.

**Comment by roooots** [comment]
Um ok, I do understand that, in principle. But then why do these pages work fine with Update Scanner on my Win7 PC at work?

r.

**Comment by sneakypete81** [comment]
Good question! I guess Firefox's implementation around this area must be subtly different on different platforms. It's surprising that Javascript works with highlighted pages under Windows.
