### ISSUE TITLE
Wont' display javascript page

### ISSUE THREAD

**Issue by exposixtyseven** [sneakypete81/updatescanner#580]
Hi - 
I'm having trouble displaying pages that using javascript. I get this message:

Please enable JavaScript to view the page content.
Your support ID is: 6983897254644122394

I have enabled javascript in Firefox and I'm still getting this message.

I'm using version 70.0.1 (64-bit)

The page I'm trying to display is this one (and all related pages)

https://novascotiaimmigration.com/move-here/

I'm also having the same issue with this page (and all related pages):
https://www.ontario.ca/page/2019-ontario-immigrant-nominee-program-updates

**Comment by sneakypete81** [comment]
Update Scanner can only scan HTM, so sites that require Javascript to display content won't work.

See https://github.com/sneakypete81/updatescanner/wiki#why-do-some-websites-not-work
