### ISSUE TITLE
Feature Request: Monitor change for only selected places on page OR exclude areas from monitoring

### ISSUE THREAD

**Issue by Skyking69** [sneakypete81/updatescanner#59]
This add-on is great and I use it all the time.  I monitor several pages that change things around the periphery of the page and so I get notices of page updates that have nothing to do with what I am monitoring.  If I had the option to monitor only a defined section of a page, in some cases as small as a couple of inches, that would be very handy.  Alternatively, the ability to ignore changes to defined portions of a page.  If this is possible it would tremendously increase the usability of the add-on.  Much thanks! - Phil

**Comment by UniX1803** [comment]
That's exactly what i want too :+1:

**Comment by sneakypete81** [comment]
Thanks, this is already captured in #50 and #9.

**Comment by Skyking69** [comment]
So is there any prospect of being able to get this feature in the near
future?  Much thanks - Phillip

 

  _____

**Comment by sneakypete81** [comment]
It's a popular feature, but unfortunately I won't have time to work on it for the foreseeable future.

**Comment by photogent** [comment]
Was just writing a request for this. One of the pages I watch has a quote that is randomly generated every time the page is opened or refreshed. The end result is that every time the page is checked, there is an "Update" that is actually nothing more than a quote. 

being able to exclude that field or sidebar, or even to select the div that has the content I am actually wanting to watch for changes would make this extension absolutely perfect for me!
