### ISSUE TITLE
error

### ISSUE THREAD

**Issue by a1fa** [sneakypete81/updatescanner#60]
Hi!
how to stop **chrome://updatescan/content/scan.js:388** ?
I'm getting this error in firefox 40-42...

**Comment by sneakypete81** [comment]
Please provide a list of steps explaining exactly how to reproduce this. What does the error message say?

Also, you could try with a fresh profile and see if the problem is still present (see https://support.mozilla.org/en-US/kb/Managing%20profiles).

**Comment by a1fa** [comment]
video of the error
http://tinypic.com/r/k3kdgo/9

**Comment by a1fa** [comment]
windows 7 sp1 x64

firefox 42.0

Add-Ons:
1-Click YouTube Video Downloader 2.4.0.1-signed
Adblock Plus 2.6.11
Add-ons Manager Context Menu 0.4.2.1-signed
AutoPager Fixed 0.8.0.10.1-signed
Bookmark Permissions 15.10.10.01
Classic Theme Restorer 1.4.2
Cleanest Addon Manager 7.0.1-signed
Close n forget 0.11.6.1-signed
Default Full Zoom Level 7.5.1-signed
Downloads Window 0.5.5
Element Hiding Helper for Adblock Plus 1.3.4
FiddlerHook 2.4.8.3
Flagfox 5.1.4
Ghostery 5.4.9
Gmelius 5.7.6.1
Go to Selection 1.3.1.1-signed
Google Analytics Opt-out Browser Add-on 0.9.8
Google search link fix 1.5.2
IE Tab 2 (FF 3.6+) 5.12.12.1.1-signed
Mask My IP 1.0
Menu Editor 1.2.7
Muter 1.0.3.1-signed
oldbar 1.2.1-signed
Open Image In New Tab 1.1.1-signed
Preferences Cleaner 0.3.2
Print Edit 16.3
Resurrect Pages 3
RoboForm Toolbar 7.9.15.0
Save File to 2.5.4.1-signed
Scan Url with 2.2.rev219.1-signed
SearchLoad Options 0.8.0.1-signed
ShowIP 2.7.7.1-signed
Status-4-Evar 2015.02.06.23.1-signed
Tab Mix Plus 0.4.1.9
Text Link 5.0.2015060501
Toolbar Buttons 1.1.1
WOT 20151113

**Comment by sneakypete81** [comment]
It could be an issue with any one of those addons. Please try with a fresh profile and see if the issue persists.

If that fixes it, try disabling/enabling your other addons to see if the problem is related to one of them.
