### ISSUE TITLE
Update Scanner isn't ignoring changed numbers

### ISSUE THREAD

**Issue by UniX1803** [sneakypete81/updatescanner#61]
I enabled the function to ignore changed numbers. But it isn't working. I get updates with changed numbers.

**Comment by sneakypete81** [comment]
There is probably something else changing in the HTML of the webpage. You can check this by:
* Go to the "Old Page" view, right-click on the page and choose "This Frame"->"Save Frame As"
* Do the same for the "New Page" view

Look at the difference between the two HTML files (try http://winmerge.org or http://meldmerge.org).

If you can't see any differences, please post the URL of the page.
