### ISSUE TITLE
Doesn't show page with changes at all

### ISSUE THREAD

**Issue by demovirus** [sneakypete81/updatescanner#617]
* OS version: Windows 10 x64 1909
 * Firefox version: 68.4.1esr x64
 * Update Scanner version: 4.4.0

#### Steps to reproduce the problem:
https://www.microsoft.com/en-us/software-download/windows10
Add url. Wait for update.

#### What you expected to happen:
Changes.

#### What actually happened:
Blank page.
![US Win10](https://user-images.githubusercontent.com/25708906/72707072-659f9a80-3b81-11ea-8a22-cae173b48a03.png)

**Comment by adsamcik** [comment]
I think this is related to #580 because Microsoft seems to use javascript to render the page.

**Comment by sneakypete81** [comment]
Correct, with Javascript disabled this page doesn't load. See https://github.com/sneakypete81/updatescanner/wiki#why-do-some-websites-not-work.
