### ISSUE TITLE
Fine-grained scan interval

### ISSUE THREAD

**Issue by h-h-** [sneakypete81/updatescanner#63]
I´d like to have more possibilities to adjust the update-interval. e.g. 2 days, 3, days and so on. Not only one day and as next step a week.
BTW - I love update scanner

**Comment by sneakypete81** [comment]
In the scanning settings, use "Select scan rate and threshold using *numbers*".
See http://sneakypete81.github.io/updatescanner/preferences.html.

**Comment by h-h-** [comment]
Thanks a lot. That´s what I´ve missed.
