### ISSUE TITLE
Mobile Firefox Support

### ISSUE THREAD

**Issue by tenten8401** [sneakypete81/updatescanner#646]
No idea if this would work since I don't know much about the internals, but many desktop extensions are currently available and work on mobile FF. Might just be a setting you have to enable in mozilla dashboard, not sure. It'd be sick to have this on mobile FF since a phone's always in your pocket and easy to receive push notifications..

**Comment by sneakypete81** [comment]
Unfortunately this wouldn't be possible without a lot of work. See also #279.
