### ISSUE TITLE
Problem with Firefox 45 beta: can't dismiss an alert

### ISSUE THREAD

**Issue by JBey4you** [sneakypete81/updatescanner#66]
Hi there.

Update Scanner encounters a problem with Firefox 45 (the first beta has released today by Mozilla). When Update Scanner alerts you of a change, you can't click on the red cross to remove the alert. Plus, when you click on the alert to see the changes, a tab open but the alert stays here.

Also, it looks like Update Scanner has a problem with tabs now. When you click on an alert, a new tab open with the changes. The things is you can't change the order of any tab after that, you have to quit Firefox and launch it again to 1) remove the alert 2) be able to change the order of the tab.

I know Firefox 45 beta has just been released, but can you tell us if a fix could become available? Or Mozilla changes some things that cause problems with Update Scanner?

Thanks!

**Comment by sneakypete81** [comment]
Thanks for the report.
> When Update Scanner alerts you of a change, you can't click on the red cross to remove the alert. Plus, when you click on the alert to see the changes, a tab open but the alert stays here.

I don't see this problem. Can you post an exact set of steps to reproduce this (starting with a new Firefox profile)? Which OS are you using?

>When you click on an alert, a new tab open with the changes. The things is you can't change the order of any tab after that,

I see this too. I'll take a look.

**Comment by sneakypete81** [comment]
Please try 3.2.4beta1 from https://addons.mozilla.org/firefox/addon/update-scanner/versions
I think that should fix all of the problems you reported.

**Comment by JBey4you** [comment]
Yep, good job. The two bugs are fixed!

**Comment by sneakypete81** [comment]
I found a problem with my fix on Win10 - the alert was no longer displayed at all.
Moving the initial position to slightly on-screen seems to fix it, so I'm releasing 3.2.4beta2 with this extra tweak.
