### ISSUE TITLE
Can not show changes on this page ?

### ISSUE THREAD

**Issue by regisfr** [sneakypete81/updatescanner#69]
Hi,

First, thank you for this great add-on.

http://www.fiabitat.com/accueil/blog-2/
If I want "Show Changes" or "Show Changes in a New Tab" the page loads then blank page ?

Regards,
Régis

**Comment by sneakypete81** [comment]
Unfortunately that website uses Javascript to load its content. UpdateScanner can only scan plain HTML web pages.

You can verify this by installing the [Just Disable Stuff](https://addons.mozilla.org/firefox/addon/just-disable-stuff/) addon and selecting "Just Disable Javascript" from the Tools menu. When you go to  http://www.fiabitat.com/accueil/blog-2/ you'll see that the page doesn't load.

**Comment by regisfr** [comment]
Thanks for explanation.

Good continuation.
