### ISSUE TITLE
Mac: Alert can't be closed

### ISSUE THREAD

**Issue by travelrobb** [sneakypete81/updatescanner#70]
Hi there-

Today my Mac (Macbook Pro 2011, running 10.7.5) updated Firefox to 45.0, and with that, the Update Scanner seems to have develped a bug. The little popup window that emerges from the bottom right-hand corner of the screen when pages update no longer recedes; it just sits there vibrating. Very annoying! Is there a fix?

Thanks,
RM

**Comment by sneakypete81** [comment]
Firefox 45.0 included a change that prevented the popup dialog from closing properly. I added a workaround to the v3.2.4 release that fixed this problem, and tested it on Linux and Windows. Unfortunately I don't have access to a Mac, so it's quite possible that I introduced a bug.

1) Which version of Update Scanner are you using at the moment?
2) Please try both v3.2.3 and v3.2.4. You can a install specific version from https://addons.mozilla.org/firefox/addon/update-scanner/versions/.

**Comment by AstroMike** [comment]
I had this issue with v 3.2.0 on Mac with FF 45. (I'm not sure why it hadn't updated automatically -  the setting in Firefox was set to update add-ons automatically).

I just updated manually to 3.2.4. First scan the popup appeared and disappeared. So working for me.

**Comment by sneakypete81** [comment]
Thanks @AstroMike, glad it's working.

@travelrobb: please let us know if you still see this issue with v3.2.4.

**Comment by travelrobb** [comment]
Hi -- I apologize for not getting back to you. The situation actually 
resolved itself a day or so after I wrote -- I think several days before 
you did the workaround. I see that I'm running 3.2.4, which was last 
modified 3-12-16. I assume that was done automatically --  I don't 
recall manually updating it myself.

Thanks,
Robb
