### ISSUE TITLE
Deleting item while scanning causes it to get stuck

### ISSUE THREAD

**Issue by Keith94** [sneakypete81/updatescanner#72]
Firefox Nightly on Windows 8

Steps to reproduce:

1. Open the Update Scanner sidebar
2. Click on the Scan button
3. Right-click and delete an item further down in the list while the scan is still active

Results: The update scan becomes stuck when it reaches the item that was deleted, and further items are not scanned

**Comment by sneakypete81** [comment]
Thanks for reporting this.
I've fixed this in v3.3.1beta1. See #36 for details, and please let me know if this works for you.

**Comment by Keith94** [comment]
It's fixed for me too, I'll close this.
