### ISSUE TITLE
3.3.0 bug - incomplete translations

### ISSUE THREAD

**Issue by Pikemo** [sneakypete81/updatescanner#74]
![bug](https://cloud.githubusercontent.com/assets/22120513/18412484/239288d6-77c2-11e6-806e-71ad437a47cb.png)

**Comment by sneakypete81** [comment]
Please try https://addons.mozilla.org/en-GB/firefox/addon/update-scanner/versions/3.3.1

Thanks for reporting this.

**Comment by Pikemo** [comment]
Thanks.
