### ISSUE TITLE
Migrate to WebExtensions

### ISSUE THREAD

**Issue by Keith94** [sneakypete81/updatescanner#82]
Due to the [upcoming deprecation of XUL-based add-ons](https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/), is it possible to implement this add-on using the new WebExtensions API?

**Comment by sneakypete81** [comment]
Yes, this addon will be affected by the future deprecation of XUL addons. It will need a complete rewrite with the new API.

**Comment by StoyanDimitrov** [comment]
Just a heads-up that the data migration window closing is near: https://blog.mozilla.org/addons/2017/09/08/last-chance-migrate-user-data/

**Comment by sneakypete81** [comment]
Unfortunately it's looking unlikely that the rewrite will be ready in time. It is well underway but progress has been slow recently.

Apologies for this. The WebExtensions API is very different from what Firefox provided in the past.

**Comment by kstev99** [comment]
Thank you, your previous message leads me to believe that at least you are working on it instead of throwing in the towel as so many add-on developers are with WebExtensions.  Thanks for all of you hard work.

**Comment by Natanji** [comment]
@sneakypete81 Will you publish a WebExtension in time to migrate user data, though? The link by @StoyanDimitrov says: "In other words, even if your WebExtensions version won’t be ready until after Firefox 57, you should still publish an Embedded WebExtension before Firefox 57 in order to retain user data." I don't know how this works technically but somehow if you just publish *something* before FF 57 then you might be able to later migrate the data somehow?

**Comment by sneakypete81** [comment]
The upgrade path will be:
1. Export your Update Scanner bookmarks
2. Import the them into the new WebExtension

I've tested that this works and won't need to be done before FF57 is released.

**Comment by StoyanDimitrov** [comment]
The settings will be lost.

On 14 October 2017 16:25:22 EEST, sneakypete81 <notifications@github.com> wrote:
>The upgrade path will be:
>1. Export your Update Scanner bookmarks
>2. Import the them into the new WebExtension
>
>I've tested that this works and won't need to be done before FF57 is
>released.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/sneakypete81/updatescanner/issues/82#issuecomment-336634845

-- 
С.

**Comment by kstev99** [comment]
The settings can all be restored, there are few and 3 screenshots would capture all of the settings.  

Maybe I'm stupid though, but how to export JUST the update scanner bookmarks other than exporting all of the bookmarks to an .html file and then editing the html file.  I see no export in the options and I don't want to overwrite new bookmarks I have created in F57.

**Comment by Natanji** [comment]
@sneakypete81 But how can a user export their Update Scanner bookmarks when FF57 is already installed, therefore the extension + its data is no longer accessible in Firefox?

**Comment by sneakypete81** [comment]
FF57 exports bookmarks to a JSON file in the same way as previous versions. Update Scanner can then import just the Update Scanner pages and their settings.

**Comment by honsberg** [comment]
is there an preview ready to test?

**Comment by sneakypete81** [comment]
The first WebExtensions beta is now up! See #36 for instructions on how to install the beta.

Not all features from the legacy addon have been ported yet, and there's no documentation written.

**Comment by StoyanDimitrov** [comment]
@sneakypete81, do you have a roadmap somewhere so I don't file issues that are already planned?

**Comment by sneakypete81** [comment]
@StoyanDimitrov: yes, please raise any issues that you find important. I won't have much time to work on this too much in the next few months, but will try to prioritise bugs or regressions.

**Comment by sneakypete81** [comment]
4.0.0 was released just in time for FF3.7! Thanks everyone for your patience and help with testing the betas.
