### ISSUE TITLE
you need to enable JavaScript

### ISSUE THREAD

**Issue by Pekiglou** [sneakypete81/updatescanner#83]
Hello,

I joined my Update Scanner tu Firefox and currently monitors approximately forty pages.
All is well, and I'm really happy!
Everything except for ONE PAGE!
When US signals a change and I click on the link, I get this:

"Sorry, you need to enable JavaScript to visit this website."

and the address of this page: https://www.croquonslavie.fr/marques/jeux

Did you have already encountered this problem?

Best Regards
Pekiglou

**Comment by sneakypete81** [comment]
Unfortunately Update Scanner only scans HTML, so can't be used for websites that require Javascript to see the content. See #31.

Sorry about that, but I'm glad that it's working well for your other pages.
