### ISSUE TITLE
Can you modify this so that it will scan in seconds, or at least faster than 5 minutes?

### ISSUE THREAD

**Issue by steezespot** [sneakypete81/updatescanner#84]
Can you modify this so that it will scan in seconds, or at least faster than 5 minutes?

**Comment by Keith94** [comment]
In the Update Scanner preferences, use "Select scan rate and threshold using _numbers_" (lowest is one minute).

See http://sneakypete81.github.io/updatescanner/preferences.html

**Comment by sneakypete81** [comment]
Rapid scanning is not a use case we can really support, I'm afraid. Also, websites don't usually appreciate having such a large quantity of constant requests. Five minutes is the minimum that can be set in Update Scanner.

Your best option is probably to write a script - the Python [Requests](http://docs.python-requests.org) package is useful for this, or you could use [wget](https://www.gnu.org/software/wget/) or [curl](https://curl.haxx.se/).

**Comment by Daniel-at-github** [comment]
You could use [urlwatch](https://thp.io/2008/urlwatch/). It's a python script that monitor one or several url's. Surely is in your Linux repositories.

**Comment by SpcCw** [comment]
While I understand what the author means it is a pity. I use it for monitoring internal resources where bandwidth or server load aren't issues but five minutes are far too long sometimes. Sure there are ways to do that like using scripts but we definitely could use user friendly tool which can be deployed and used with minimal learning curve.

Personally I would think about hiding this under some "advanced options" checkbox.
