### ISSUE TITLE
No visible slidebars on New Entry window

### ISSUE THREAD

**Issue by bdcomp** [sneakypete81/updatescanner#88]
There is no visible slidebars on New Entry window.
Although the functionality is still present, so it usable by guessing.

Update Scanner 3.3.1
Firefox 50.1.0
Kubuntu 16.10 64bit

**Comment by sneakypete81** [comment]
Perhaps this is a problem with Firefox + KDE?
Could you try this with a different desktop environment?

Do you have any other extensions that use Firefox slidebars and work correctly?

**Comment by bdcomp** [comment]
Thanks for the addon and a quick reply.

No other addons with slidebar or DE on this PC.

As I use Update Scanner often, I am pretty sure this issue is new, since 2 Firefox versions ago, max.

**Comment by sneakypete81** [comment]
I have to assume this is KDE-specific - Ubuntu Unity is working for me.

This will be fixed as part of #82.

**Comment by sneakypete81** [comment]
Now using HTML range inputs in v4.0.0, so hopefully this is no longer a problem.
