### ISSUE TITLE
Use 32x32 icon in menu panel

### ISSUE THREAD

**Issue by Keith94** [sneakypete81/updatescanner#90]
The 18x18 icon is too low res for the menu panel/customization palette.

![firefox_2017-01-08_22-29-23](https://cloud.githubusercontent.com/assets/5490615/21758564/eac69176-d5f1-11e6-9dbc-4b6122a5f83b.png)

**Comment by sneakypete81** [comment]
Thanks @Keith94, icon size requirements have changed a bit since Update Scanner was first developed. Icon sizing will be reviewed as part of #82.

If anyone would like to submit an updated icon design, that would be much appreciated!

**Comment by sneakypete81** [comment]
Fixed in v4.0.0
