### ISSUE TITLE
Don't show 'Properties' for folders and separators

### ISSUE THREAD

**Issue by Keith94** [sneakypete81/updatescanner#93]
In the Update Scanner sidebar, folders and separators have the 'Properties' option when right-clicking them. However, clicking on Properties doesn't seem to do anything, except show errors in the browser console. Separators also have other unnecessary options.

`TypeError: PlacesUIUtils.showItemProperties is not a function[Learn More]  updatescan.js:333:10`

`NS_ERROR_MALFORMED_URI: Component returned failure code: 0x804b000a (NS_ERROR_MALFORMED_URI) [nsINavBookmarksService.getBookmarkURI]`

**Comment by sneakypete81** [comment]
Thanks, this will be handled as part of #82.

**Comment by sneakypete81** [comment]
Fixed in v4.0.0
