### ISSUE TITLE
Transfer data / prefs

### ISSUE THREAD

**Issue by keithy397** [sneakypete81/updatescanner#94]
Hi.  My Firefox Profile is getting a bit old and knackered, time to move on to a new one - after a looong time with the same Profile.  Is there any way I can transfer my data etc to the new Profile?

Cheers,
Keith

**Comment by sneakypete81** [comment]
Yes you can do this, see #54, #35 and #8.
https://support.mozilla.org/kb/restore-bookmarks-from-backup-or-move-them

This won't export the downloaded page copies - they are stored in your profile folder in a subdirectory called "updatescanner". I'm not sure how best to transfer these to a new profile, you could try copying them over before importing your bookmarks.
