### ISSUE TITLE
Update Scanner - unable to import bookmarks

### ISSUE THREAD

**Issue by tomrich84** [sneakypete81/updatescanner#945]
I am unable to import bookmarks (JSON file) into update scanner. I have just reinstalled the app on Firefox (version 93.0 64-bit) and have a JSON file from another pages scanner extension. When I try and import (well using the restore function in the extension) it begins the process but then just says failed to restore pages.

![Capture](https://user-images.githubusercontent.com/34336677/138051350-9d4c70d5-62cd-4b46-bc9d-339fa0a3657d.PNG)

**Comment by sneakypete81** [comment]
Update Scanner will only recognise JSON files that it previously created. Unfortunately you won't be able to use this function to import bookmarks from a different extension.
