### ISSUE TITLE
Link in Update Scanner stops Firefox

### ISSUE THREAD

**Issue by AlexN-114** [sneakypete81/updatescanner#95]
Since Firefox **52** I had problems with **Update Scanner**. I got a message that a script does not response and if I click to Debug, I came to Update Scanner Source. But even which button (Ignore, debug or stop) I pressed, a short time later Firefox stopped all working.
In the meantime, I assume that this Url [https://www.cmxlog.com/13/i9100/](https://www.cmxlog.com/13/i9100/)  made the problem. Since I removed it, all seems to work well.

/Alex

**Comment by sneakypete81** [comment]
Sorry for the delay that link seems to be dead, has it moved?

**Comment by AlexN-114** [comment]
Yes, the link is dead. My impression is, that when a web site is dead or didn't response for any reason Update scanner stops Firefox. This behaviour is since Firefox 52. As long as I had also a Firefox version 51 the dead link didn't disdurb. 
If I remember correct, I got a sometimes a message that the script updatescanner.js line=**302** doesn't responce. [Ignore] [Stop] [Debug]

**Comment by sneakypete81** [comment]
> My impression is, that when a web site is dead or didn't response for any reason Update scanner stops Firefox.

I don't see this behaviour. Are you still getting this problem?

**Comment by AlexN-114** [comment]
I have still this problem. 
What I found with this problem:
1.) It doesn't happen, when I click **Abort** in the dialog for the **Master password**.
2.) It happens rare, when I have no open Firefox tab with the WME (https://www.waze.com/editor/).
3.) It doesn't happen, when I deactivate **Update Scanner**. :(

Is it possible to export my Update Scanner **environment**/**options**/**link list** to send it to you?

**Comment by sneakypete81** [comment]
Please check with v4.0.0 - hopefully this is no longer a problem.

**Comment by AlexN-114** [comment]
Thank you for your work.
I did it and I had so long no problems, but I will watch it in the next time (because a the moment I have only few pages to scan).
