### ISSUE TITLE
3.2.4: HTTP Auth no longer silent

### ISSUE THREAD

**Issue by nummacway** [sneakypete81/updatescanner#97]
Running Firefox 45esr. Since 3.2.4, the HTTP Auth window appears when an HTTP Auth website is checked, even when credentials are in the link update scanner uses. This worked silently before. The new window does not even have the credentials pre-set.

**Comment by sneakypete81** [comment]
Updatescanner doesn't attempt to support authentication.

BTW: are you sure that this is working in 3.2.3? I don't think there were any changes in this area around then.

**Comment by nummacway** [comment]
Oops, I missread the date the plugin was updated. I read "updated 23 Apr 2017" in Firefox which was conincident with the issue appearing. But it was updated on 23 Apr 2016. Sorry!

**Comment by sneakypete81** [comment]
Unfortunately we can't easily support authenticated websites.
